### ISSUE TITLE
Donate 1 million causes error. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#10]
Steps:
1. User opens the Donate page. 
2. User selects the term as Yearly. 
3. User enters a number as 1 million. 
4. User clicks Donate with credit card button. 
5. User clicks Submit payment button. 

Expected Result:
The payment would be processed successfully.

Actual Result:
The payment could not be processed. An error comes out. 
![4](https://user-images.githubusercontent.com/42002784/43529738-7fd18a5c-95de-11e8-93fe-28b8ed928bc5.png)

**Comment by d33pspace** [comment]
Let's make the acceptable range US$0.50 - $100,000.00.

**Comment by elainetao829** [comment]
Verified based on the 1st comment and failed.
1. Try to donate 100,000.00, the system rejects and said no more than 100,000.00. But 100,000.00. should be acceptable.

2. Try to donate 0.4 and the unhandled exception occurred again.

**Comment by kolte** [comment]
this is fixed, please review

**Comment by d33pspace** [comment]
@elainetao829 Please take a look.

**Comment by elainetao829** [comment]
Verified and passed.
