### ISSUE TITLE
The font size is not the same on the Campaign payment page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#100]
Actual Result:
For both Chinese and English, the size of the message explaining the Name field, is smaller than the size of the message explaining the address.
![image](https://user-images.githubusercontent.com/42002784/45260840-5a344f00-b424-11e8-987a-1933429e3e2c.png)

![image](https://user-images.githubusercontent.com/42002784/45260841-5e606c80-b424-11e8-852e-70edb60f12f4.png)

Expected Result:
@d33pspace as I checked with my eyes, the size of the normal payment page is the same as the 2nd messages above,, i.e. we should enlarge the 1st messages here. Could you please check in the code to see if I'm right here?

**Comment by d33pspace** [comment]
Yes, you were right on. I corrected several inconsistencies in the code across the four similar pages (donate page new card payment, donate page existing card payment, campaign page new card payment, and campaign page existing card payment). Please give all these pages another sweep in English and Chinese to make sure everything looks good.

**Comment by elainetao829** [comment]
Verified the four pages and everything looks good now.
