### ISSUE TITLE
The Chinese improvement for adding external accounts.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#102]
1. English: External log in was added.
Wrong Chinese: 外部登录已添加。
Correct Chinese: 第三方登录账户已添加。

2. English: The external log in was removed.
Wrong Chinese: 外部登录已被删除。
Correct Chinese: 该第三方登录账户已被删除。

3. Button REMOVE
Wrong Chinese: (not translated)
Correct Chinese: 删除
![image](https://user-images.githubusercontent.com/42002784/45304364-8649f000-b54a-11e8-9110-1526ca68273f.png)

**Comment by d33pspace** [comment]
I made these changes. Please take a look. Thanks for describing the translation issues in this way - it makes it very easy to update!

**Comment by elainetao829** [comment]
Verified and confirm fixed.
