### ISSUE TITLE
PDF format

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#105]
Expected Result:
There should now be some fine print on the Chinese PDFs (in Chinese), but it should not refer to the 501(c)(3). It should only say something along the lines of "no goods or services were provided." And of course I'm not talking about the font weight when I say "fine print" - I'm referring to the legalese at the bottom of the page.

Actual Result:
There is no fine print on Chinese PDF any more. 

@d33pspace can you please provide the Chinese words to avoid any confusion here?

**Comment by d33pspace** [comment]
Hi @kolte I'm sorry I think there was a little confusion here. Please allow the legal phrase about the 501(c)(3) to show up at the bottom of the Chinese version PDF. The correct translation is already in the ManageController resource file, so it should show up with accurate Chinese translation. The font size is fine.

**Comment by kolte** [comment]
@d33pspace 
it's already there, I checked for both english and chinese version. Please let me know if it's something else

**Comment by d33pspace** [comment]
Yes, fine print looks good. I'm sorry just one more change. On English PDFs, in the table, please use the date format Mmm DD, YYYY. The date format in the heading can stay the same with the full month name, but if it's easiest to change all the dates please use Mmm DD, YYYY. Screenshot below.

![screenshot 215 _li](https://user-images.githubusercontent.com/13606352/45520860-e9a77c80-b7ed-11e8-8352-dccbf1410bf2.jpg)

**Comment by d33pspace** [comment]
@elainetao829 I'm happy with the fine print and date format on the PDFs now. Please take a good look yourself.

**Comment by elainetao829** [comment]
Confirm the date format is fine on both English and Chinese PDFs.
Confirm the fine is fine on Chinese PDF.  

One question left, the name of the PDF file for both Chinese and English is Renewal.pdf now. It was correct in the past. 

@d33pspace can we change back to 
Renewal Donate History (for English PDF)
日新捐赠记录 （for Chinese PDF)

**Comment by d33pspace** [comment]
Great. Thank you. We're troubleshooting the file name in #23 as possibly related to the trouble we're having downloading the PDF on Xiaomi, etc. This is still unresolved but I'll close this issue and we'll address the file name there.
