### ISSUE TITLE
The title and the button of the viewing history confirmation email are not translated.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#106]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/45363291-b4dad000-b609-11e8-9447-360f5d9b621d.png)

Expected Result：
Title: 查看捐赠历史确认
Button: 确认查看捐赠历史
![image](https://user-images.githubusercontent.com/42002784/45363413-0e42ff00-b60a-11e8-9e6f-87cb79162d02.png)

**Comment by elainetao829** [comment]
1. Yes I think the it should starts with 
xxx,
您好！
And I agree we can leave this to next stage.

2. Please delete my account 46208601@qq.com again so that I can trigger the email again :)

**Comment by d33pspace** [comment]
Deleted your email.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
