### ISSUE TITLE
The message of sending confirmation email successfully is not translated. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#107]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/45363471-329edb80-b60a-11e8-90d7-7a5d07ba090b.png)

Expected Result:
@d33pspace do you want to update the English words here? It says link for view(ing?) invoice history? And also it's a link for confirm viewing...but it's too long maybe.
I'll provide the Chinese after you confirm the English here.

**Comment by d33pspace** [comment]
Thanks. I used "Confirmation email sent successfully." and "确认邮件发送成功。" If my own translation is acceptable this is ready for testing, if not, just let me know the better translation! :)

**Comment by elainetao829** [comment]
Verified and confirm fixed.
