### ISSUE TITLE
The invoice confirm history is not translated correctly.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#108]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/45364346-7eeb1b00-b60c-11e8-9a74-3dc463807a02.png)

Expected Result:
1. The title and the tab name should be updated into: 查看捐赠历史确认
2. There is an extra "请“ underlined as highlighted above. Please delete that.

**Comment by d33pspace** [comment]
Thanks. Fixed this. Ready to test.

**Comment by d33pspace** [comment]
Thanks. Fixed this. Ready to test.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
