### ISSUE TITLE
Translation of errors during payment process

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#109]
I believe the error message indicated in the screenshot below is coming from Stripe. We need to translate into Chinese. The correct translation is already in the DonationController resource file. 

This may apply to Payment, RePayment, CampaignPayment and CampaignRePayment. This also applies to the account management Card tab. 

![image](https://user-images.githubusercontent.com/42002784/45365002-2288fb00-b60e-11e8-8eec-c15d392ca4e5.png)

**Comment by elainetao829** [comment]
Verified and confirm fixed.
