### ISSUE TITLE
Round corners

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#11]
Please implement round corners in the following settings similar to our buttons:

![screenshot 83 _li](https://user-images.githubusercontent.com/13606352/43552535-6bb2675a-961d-11e8-91e8-5d9de6b6e72f.jpg)

![screenshot 84 _li](https://user-images.githubusercontent.com/13606352/43552544-77a32fb8-961d-11e8-8f79-97c53db719e7.jpg)

![picture1](https://user-images.githubusercontent.com/13606352/43552581-9f5fd34e-961d-11e8-80aa-2767eadd5e9b.png)

![picture2](https://user-images.githubusercontent.com/13606352/43552603-b14dd0b0-961d-11e8-914c-236e4da1e587.png)

![screenshot 89 _li](https://user-images.githubusercontent.com/13606352/43552754-6749ac7c-961e-11e8-92a6-002fb44bceb9.jpg)

**Comment by d33pspace** [comment]
Please add a few pixels space between the Log Out and language selection buttons as indicated in the screenshot below:

![screenshot 102 _li](https://user-images.githubusercontent.com/13606352/44067131-7df6f678-9fa6-11e8-9dd1-a0cb7dba2b88.jpg)

**Comment by kolte** [comment]
this is fixed, please review

**Comment by d33pspace** [comment]
@kolte This is looking great. Two small things I'd like changed: 

(1) Space between Log Out and language selection button is a little too much, please reduce by 1/2 (for example, if it's 6 pixels, reduce it to 3). See screenshot below.

![screenshot 157 _li](https://user-images.githubusercontent.com/13606352/44381367-8e61d180-a542-11e8-9a85-7e382195ce6a.jpg)

(2) On normal links, the text shifts to the right one or two pixels upon hover over. I think the best way to fix this might be to include the right and left padding during the normal state. In other words, padding amount should not change.

![screenshot 155 _li](https://user-images.githubusercontent.com/13606352/44381403-c79a4180-a542-11e8-8b11-1bfb70e395d3.jpg)

**Comment by elainetao829** [comment]
Verified and confirm fixed.

**Comment by d33pspace** [comment]
I'm sorry to nitpick this... 

1. The text shifting is corrected, thank you, but the right and left padding is too much on this type of link, so the underline extends too far beyond the text. Please reduce the right and left padding so that the inverse just overlaps the text by 1 or 2 pixels. Screenshot below.

2. I've noticed in Edge that by clicking on a link and waiting for the next page to load, there is a double-underline. Can we prevent this? Screenshot below.

![screenshot 186 _li](https://user-images.githubusercontent.com/13606352/44906636-0f417a00-ad48-11e8-8b72-172f9905c363.jpg)

![screenshot 188 _li](https://user-images.githubusercontent.com/13606352/44906823-942c9380-ad48-11e8-9b42-40973bb5584e.jpg)
