### ISSUE TITLE
Proper format of emails sent by website

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#110]
For both types of emails sent by the website (password reset and invoice history confirmation) please use simply "Hi there!" in English and ”你好！“ for the greeting at the top. Do not use the person's name. Note the comma is replaced by an exclamation point for both English and Chinese.

**Comment by d33pspace** [comment]
I am thinking it's best here

**Comment by elainetao829** [comment]
Hi @d33pspace 

For the Chinese reset password email, there is a 您好 already and now it's duplicated. Please delete 您好 and keep 你好 to make sure it's the same with other emails.
![image](https://user-images.githubusercontent.com/42002784/45596281-76b82480-b9ec-11e8-8a9e-2126a1e63d4e.png)

**Comment by d33pspace** [comment]
Superfluous 您好 removed.

**Comment by elainetao829** [comment]
Verified and confirm passed.
