### ISSUE TITLE
The unsubscription page is not translated correctly.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#113]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/45530002-f393a480-b81a-11e8-9ab7-beb79498a9ea.png)

Expected Result:
还有一步…… --> 还差一步……

用下面的按钮…… --> 请点击下面的按钮退订所有邮件。

Button: 退订所有邮件

Tab Index: 退订

For the English page, the tab index should be: Unsubscribe (or Unsubscription?)

**Comment by elainetao829** [comment]
2. Actual Result:
![image](https://user-images.githubusercontent.com/42002784/45530093-7e749f00-b81b-11e8-858f-219e6d9f29ba.png)

Expected Result:
您已取消订阅所有续订通讯。  --> 您已退订所有邮件。

**Comment by d33pspace** [comment]
Thank you. I've made these changes. Please confirm.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
