### ISSUE TITLE
Email subscription confirmation page translation

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#116]
I've replaced the email subscription confirmation below with 感谢您对日新中心的兴趣！Is this alright?

![screenshot 217 _li](https://user-images.githubusercontent.com/13606352/45542714-408c7080-b845-11e8-8af0-81a88fd6e68c.jpg)

**Comment by elainetao829** [comment]
Yes that's right.
Verified and confirm fixed.
