### ISSUE TITLE
Add spinners to buttons that require a wait

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#117]
(1) Please put the 'please wait' spinner on the unsubscribe page submit button as well:

https://staging.renewal365.org/unsubscribe?email=jimmy@renewal365.org

(2) And also on "Send confirmation link" button on History tab.

**Comment by d33pspace** [comment]
@elainetao829 Please check for these two "please wait" spinners and make sure this resolves the problem you were having with the multiple confirmation emails sent you mentioned in #66.

**Comment by elainetao829** [comment]
Hi @d33pspace,
The functionality works fine. The problem in #66 has been fixed.

Just one last thing here, the spinner is always in English even the language of the page is Chinese. Can we translate it?
PLEASE WAIT --> 请稍等

**Comment by d33pspace** [comment]
Hi @kolte All 'please wait' spinners are working great. Thank you. Please add Chinese translation for 'please wait' -> 请稍等

**Comment by elainetao829** [comment]
Hi, this is not fixed yet. Please check again.

![image](https://user-images.githubusercontent.com/42002784/45797603-f4c04800-bcd8-11e8-9022-b9fe11314020.png)

**Comment by elainetao829** [comment]
And here needs to be fixed as well.
![image](https://user-images.githubusercontent.com/42002784/45798519-c0e72180-bcdc-11e8-8f49-7ef8bf0812c2.png)

**Comment by kolte** [comment]
![screenshot_20180920-113534](https://user-images.githubusercontent.com/8025877/45799334-bf146280-bcca-11e8-9d69-7d03cab31dda.jpg)
I tried it and it looks like in chinese, can you please check again and let me know if this is any specific scenario we are missing here?
@elainetao829

**Comment by elainetao829** [comment]
Hi @d33pspace,
Verified and confirm fixed now. I think it was the cache problem. I cleared all the history now and tried again. Everything looks fine.
