### ISSUE TITLE
The buttons and content of history showed up repeatedly on WeChat.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#118]
Steps:
1. Open the website from WeChat.
2, Log in with an account has a history, e.g. invoices@renewal.org.cn.
3. Go to tab History of Account Management.
4. Don't need to click any button, just wait for a while.

Actual Result:
The buttons and content are repeatedly.

![1](https://user-images.githubusercontent.com/42002784/45557059-5878ea00-b86f-11e8-84c0-9d413ef1c90d.jpg)
![2](https://user-images.githubusercontent.com/42002784/45557062-5878ea00-b86f-11e8-85d9-13e09a98605a.png)

**Comment by d33pspace** [comment]
@elainetao829 Hi Elaine, yesterday I noticed some similar odd behavior on a Xiaomi from the Xiaomi browser. It didn't do this just by waiting, but when I clicked the buttons multiple sets of tables and buttons would show up. But today I tested on my iPhone WeChat browser, and my Xiaomi WeChat browser and Xiaomi browser and couldn't reproduce this. Strange.

Could you mess with this a little further and see if it's still happening and possibly try a few different browsers/devices to see if we can find out what's going on?

**Comment by elainetao829** [comment]
Hi @d33pspace 
I cannot reproduce this now either, for both Xiaomi Wechat and Xiaomi Browser :) I would suggest we close this for now until it happens again.
