### ISSUE TITLE
Test default language, currency

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#119]
Now that production is updated please test the default currency suggested by the site. Visiting the site from a mainland Chinese IP address should suggest CNY/Alipay. Visiting from an IP address outside China should suggest USD/credit cards.

The default language of the site should be determined by the device or browser settings. 

If the user makes a change to either the language or currency the selection should be the same even when the browser is closed and reopened. Of course you'll need to clear your cookies occasionally to test this properly.

Actually the default language determination should also work fine on staging, but default currency will only work properly on production.

**Comment by elainetao829** [comment]
Hi Jimmy,
One question,
Will the default currency be independent from the language? Or it's always consistent with the language?
If I set the language of the browser to Chinese, then open the website with a foreign IP, which currency should I see?

**Comment by d33pspace** [comment]
Good question. Yes, currency is derived from IP address and independent of language. Language is derived from browser setting and independent of currency. Then whatever currency and language you select yourself should be remembered next time you visit the site.

**Comment by elainetao829** [comment]
Tested and everything works fine.
