### ISSUE TITLE
Thank you message incorrect for new subscription of first-time customers

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#12]
The thank you confirmation message is incorrect for first-time customers who create a recurring gift (subscription).

To recreate this issue:

1. Select a recurring (monthly/quarterly/yearly) gift.
2. Create a new user account.
3. Complete the gift.
4. The thank you message is incorrect. This applies to both Donate page gift and Campaign page gifts.

*When testing please confirm both English and Chinese language are correct.

See screenshot here:

![screenshot 92 _li](https://user-images.githubusercontent.com/13606352/43670536-50666872-97bf-11e8-922c-c4a1eb36c55f.jpg)

**Comment by kolte** [comment]
I haven't been able to replicate this issue can you please test this on staging server?

**Comment by d33pspace** [comment]
Yes, this issue is present on staging. Just follow the steps above. Key points are (1) must be a recurring gift (monthly/quarterly/yearly) and (2) must be a newly registered user.

Issue present with either beginning with donate page or campaign page.

**Comment by d33pspace** [comment]
Elaine this is fixed, can you please do some testing and also confirm the Chinese version? Note as detailed above this message is only visible for recurring gifts for new customers who have not made a gift before.

**Comment by elainetao829** [comment]
The Chinese wording is not OK now.
Actual Result:
交易成功！你的$15.70捐赠会自动的重复monthly。要随时管理或取消订阅，请点击以下链接。

Expected Result:
扣款成功！你将会每月捐赠$15.70。要管理或随时取消定期捐赠，请点击以下链接。

**Comment by d33pspace** [comment]
Girish, the English here has also reverted to something incorrect. Can you please correct the English and then make sure the Chinese is functionally similar, and that the frequency (monthly | quarterly | yearly) is at least being translated into Chinese?

**Comment by kolte** [comment]
this is fixed, please review

**Comment by d33pspace** [comment]
@elainetao829 Please take a look and see where we are with this one when you can (English and Chinese).

**Comment by elainetao829** [comment]
Hi,

The Chinese and English are mixing sometimes. Please fix this.

![Uploading image.png…]()

**Comment by elainetao829** [comment]
![image](https://user-images.githubusercontent.com/42002784/44305129-e06bf100-a3a2-11e8-8b51-673c868b6535.png)

![image](https://user-images.githubusercontent.com/42002784/44305131-e661d200-a3a2-11e8-9dd1-3d4b3986d0a1.png)

**Comment by d33pspace** [comment]
@kolte Please take a look. @elainetao829 In the future please include the URL and the steps taken to produce the error - - this one is especially tricky because there are several paths to the same page and there can be different outcomes.

**Comment by elainetao829** [comment]
Confirm fixed.
