### ISSUE TITLE
Add validation for preference update

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#120]
On the email preference update form:
https://staging.renewal365.org/preference?email=jimmy@renewal365.org&salutation=Jimmy

Please add validation for the email field to confirm it's a valid email address, also make the salutation field required. Please use .NET Core-style validation or a browser message.

Messages:
ENGLISH: Please enter a valid email address.
CHINESE: 请输入有效的电邮地址。

ENGLISH: Please enter your name.
CHINESE: 请输入你的名字。

**Comment by elainetao829** [comment]
Verified and passed.
