### ISSUE TITLE
While trying to open he PROD website, there is a not secure error message.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#121]
![image](https://user-images.githubusercontent.com/42002784/45692359-288e5700-bb8d-11e8-8fd6-ffd4df4cc031.png)

Hi Jimmy, 
Please check this and see if we can change the configuration. The insecure message affects the user experience for sure.

**Comment by d33pspace** [comment]
Oh! Thank you for catching this! I had not uploaded our SSL certificate to China Azure yet. Should be working with no errors now. Note that to test this your VPN must be off, and you might also clear your browser cache.

**Comment by elainetao829** [comment]
Hi Jimmy,

The original problem has been fixed. 
But I also found http://www.renewal.org.cn is unable to be accessed.. I thought it was the same as https. But I think you are aware of this.

![image](https://user-images.githubusercontent.com/42002784/45724767-3a521780-bbea-11e8-91c1-37ba5025fc84.png)

**Comment by elainetao829** [comment]
Please feel free to close this ticket if it is not a problem.

**Comment by d33pspace** [comment]
Oh no! That's annoying. It used to not be that way, I wonder if the SSL certificate change possibly triggered it. Anyway, we're working on the ICP filing requirements but of course they're next to impossible. I'm not getting that message in Shanghai yet - it could be regional.

Thanks. Closing for now.
