### ISSUE TITLE
The Chinese tranlsation on the history PDF when there is no name maintained.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#122]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/45693155-0c8bb500-bb8f-11e8-87be-a26d5166699a.png)

Expected Result:
请在个人资料页输入您的姓名。

**Comment by d33pspace** [comment]
Thank you. Done.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
