### ISSUE TITLE
Log in with account A, and open the email confirmation link for account B, the website still shows log in with account A.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#123]
Steps:
1. Open the website with a browser, and log in with account A. 
OR
1. Open the website with a browser, log in with account A and select remember my account. After that close the website.

2. Open a new tab of the browser, and open the history confirmation email for account B.
Actual Result:
The website opens a confirmation successful page, this should be for account B. But on the top right it still shows account A.

![image](https://user-images.githubusercontent.com/42002784/45724469-f90d3800-bbe8-11e8-83ad-e334243810c9.png)

![image](https://user-images.githubusercontent.com/42002784/45724489-117d5280-bbe9-11e8-985d-0fc59d26e408.png)

**Comment by d33pspace** [comment]
@kolte Please consider this low priority but take a quick look after you resolve the other issues. If this is something easy to fix, please take care of it.

**Comment by elainetao829** [comment]
I sent the confirmation email, and clicked the link from the email --- I didn't see the successful page. The website opens the home page directly. Please check this again, thanks.

**Comment by d33pspace** [comment]
@elainetao829 Please give this another look.

**Comment by elainetao829** [comment]
No the confirmation link leads to an error page.

![image](https://user-images.githubusercontent.com/42002784/45814777-3c5ec800-bd09-11e8-8ed5-d6472d9493fe.png)

If the original ticket is something complicated, maybe we can ignore that and roll the code back...

**Comment by elainetao829** [comment]
Verified and confirm fixed.
