### ISSUE TITLE
The new password needs to follow the rules when user is resetting the password.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#125]
Expected Result:
When user is registering a new account, the system would require the password to be,
contains at least 1 digit
contains at least 1 non alphanumberic character
contains at least 1 lower case
contains at least 1 upper case 

The same rule should apply to the password field when user is trying to reset the password.

Actual Result:
If user is entering some password does not meet the rules above, e.g. 123456, the system would says reset successfully. But user is not able to log in with 123456, but can only log in with the old password, e.g. the password is not reset successfully on the back end.

**Comment by kolte** [comment]
@elainetao829 @d33pspace 
I am not able to replicate this issue, can you please confirm the browser you are testing in?

**Comment by elainetao829** [comment]
Dear @kolte ,
Thanks for your explanation on Upwork. I was using a link from an old email. Probably the email/account was deleted afterwards at some point and I created it again. So the old link is not acting properly.
However, I noticed both English and Chinese error messages when user entering a very simple password were not correct. The system empties the password and confirm password fields and display the error messages as below,
![image](https://user-images.githubusercontent.com/42002784/46084252-d1643400-c1d5-11e8-86bf-347d87d12747.png)

Please change the messages to be the same as Register page, i.e.

Passwords must have at least one lowercase ('a'-'z'). 
密码必须包含至少一个小写字母（“a”-"z"）。

Passwords must have at least one uppercase ('A'-'Z').
密码必须包含至少一个大写字母（“A”-"Z"）。

Passwords must have at least one non alphanumeric character.
密码必须包含至少一个非字母数字字符。

Passwords must have at least one digit ('0'-'9').
密码必须包含至少一个数字（“0”-"9"）。

**Comment by kolte** [comment]
please provide me translation for below @elainetao829 

Password must contain at least one special character, one number, one lowercase and one uppercase letter.

**Comment by elainetao829** [comment]
密码必须包含至少一个特殊字符、一个数字、一个小写字母和一个大写字母。

@kolte I didn't see this message on the Register page (and I don't know when it should show out). Please use this for the Register page too if possible.

**Comment by elainetao829** [comment]
Hi,
I'm sorry I can't pass this. But I know it's weekend already. @d33pspace maybe you can take a look and change the error message at least?
Now the error message comes out at once, which is different from the register page, but that's fine. However, at least there would be 6 characters. And when I'm entering a password under 6 characters, there is no related error message but the system does not allow me to proceed either (click the Reset button nothing happens except the irrelevant error message comes out).
![image](https://user-images.githubusercontent.com/42002784/46218299-d2809700-c376-11e8-90bb-77da4d698765.png)

**Comment by d33pspace** [comment]
@kolte Please take one more look at this - seems that the error message is not displaying for passwords under 6 characters.

@elainetao829 In case Girish needs it will you please provide the translation for "Passwords must be at least 6 characters"? Also, provide this translation integrated with the combined error message you provided above.

**Comment by elainetao829** [comment]
I just noticed the Register page is changed and is having the same bug now.

Passwords must be at least 6 characters" --> 密码应至少为六位。

**Comment by elainetao829** [comment]
Verified and it's done now (though not assigning to me)
