### ISSUE TITLE
The Change Password page is mixing Chinese with English.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#126]
1. User opens the Change Password page in English.
2. User checks the page.

Expected Result:
Everything should be in English.

Actual Result:
The name on the tab, the title and the button are in Chinese.
![image](https://user-images.githubusercontent.com/42002784/46221287-3dce6700-c37f-11e8-8cbc-db9ef7540d69.png)

**Comment by d33pspace** [comment]
Could you check this out please, @kolte

**Comment by elainetao829** [comment]
Verified and it's done now.
