### ISSUE TITLE
Donate campaign page: the donation amount should be in an increasing sequence?

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#128]
Steps:
1. Open the Donate campaign (from the newsletter) and checks the 3 amounts in the list.

Actual Result:
Now the amounts in the list are:
$70.65
$47.1
$94.2

Expected Result:
It's not strictly defined, but I think the amount should be in an increasing sequence (from the smallest to the biggest), just as the normal Donate page. 
In short, the list should be
$47.10
$70.65
$94.20

**Comment by d33pspace** [comment]
Hi Elaine, thank you for catching this, but in this case it's intentional. On occasion we make the first amount the "suggested" amount, with the following two being less and more depending on the preference of the donor.
