### ISSUE TITLE
There is an extra error message for both Donate and Donate Campaign page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#129]
Steps:
1. User opens Donate or Donate Campaign page (for both Chinese and English).
2. User enters an amount as 100000.00.  (including the last period)
3. User clicks the Donate with Credit or Debtor Card button.
4. The system shows out error message. User checks the error message.

Actual Result:
There is an extra error message The value '100000.00.' is not valid for DonationAmount.
![image](https://user-images.githubusercontent.com/42002784/48947170-3be1e800-ef6b-11e8-9b5d-2887f4e21607.png)

Expected Result:
Remove the extra error message. 
Please remove the message for:
Donate page (English and Chinese)
Donate Campaign page (English and Chinese)

**Comment by d33pspace** [comment]
Thank you for catching this. Since it's an edge case I'm going to pause this issue to work on later.

**Comment by elainetao829** [comment]
Not reproducible on 2021-02-28, so set to close.
