### ISSUE TITLE
Customers may stumble upon staging

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#13]
At least one customer has somehow stumbled upon our public staging environment and attempted to make a gift. Do you have an idea of how we could prevent this? 

You may have a better idea but one I thought of is displaying a warning message on the sign in page unless ASPNETCORE_ENVIRONMENT is set to Production. Such as, "You've stumbled up on our testing server! Please click here to proceed to our website: https://www.renewal.org.cn." 

See screenshot below:

![inkedstaging-error_li](https://user-images.githubusercontent.com/13606352/43672376-32cce92e-97df-11e8-8b08-4a78e5ec65f0.jpg)

**Comment by d33pspace** [comment]
The update here looks great, just reopening this to remind me to refine and translate the message and test on production.

**Comment by d33pspace** [comment]
Elaine can you please take a look at this and offer an appropriate Chinese translation?

**Comment by elainetao829** [comment]
I remember there was a Chinese translation before and it was good. 

But I can translate as well, as below

您误入了我们的测试页面！请点击这里回到我们的网站https://www.renewal.org.cn。

**Comment by d33pspace** [comment]
Thanks. Please confirm and close. Note that I used a colon before the link in lieu of a period after because it makes the code a little cleaner. If this is weird in Chinese just let me know and I'll make the change.

**Comment by elainetao829** [comment]
@d33pspace It's still in English to me. Could you please have a look?

![image](https://user-images.githubusercontent.com/42002784/44247117-bedcff00-a214-11e8-9595-ffc648037d54.png)

**Comment by d33pspace** [comment]
Should be fixed now! Check today after 10a.

**Comment by elainetao829** [comment]
Verified and fixed.
