### ISSUE TITLE
Delete a subscription more than once, the system will open a 404 page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#130]
Precondition:
User has been made some subscription before.

Steps:
1. User opens Account Management page.
2. User clicks the Cancel button of one subscription, and confirms to cancel it. The system starts loading, but the Cancel button for that subscription is still there.
3. User clicks the Cancel button again.

Actual Result:
![image](https://user-images.githubusercontent.com/42002784/48963977-b6495100-efd9-11e8-82cc-54ee39db4b5b.png)

Expected Result:
There should be some loading sign to prevent user clicking the Cancel button again.

**Comment by d33pspace** [comment]
Noted and paused, thank you!

**Comment by elainetao829** [comment]
Reproducible on 2021-02-28.
![image](https://user-images.githubusercontent.com/42002784/109410352-df38c780-79d4-11eb-86d0-c0b29838a6eb.png)

**Comment by elainetao829** [comment]
Tested fine on 2021-03-04.
