### ISSUE TITLE
When there is only 1 record in "All History", what should be the time range on the PDF?

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#133]
Precondition:
There is only one history record.

Steps:
1. User opens user management.
2. User opens tab History.
3. User clicks All History. The only record is on the page.
4. User clicks PDF.
5. User checks the time range on the PDF.

Actual Result:
The time range is only 1 day, which is the date of the record.
![image](https://user-images.githubusercontent.com/42002784/48976387-8b3a2c80-f0c1-11e8-8ed4-3fa753129717.png)

Expected Result:
I think it maybe confusing to the user or the reader of the PDF (they may think: could there be any more record or PDF?)
To avoid confusion, I think if user is downloading the All History PDF, no matter how many records are there (1--N), we could display:
Your giving history:    ------ for English PDF
您的捐赠记录：     ------- for Chinese PDF

**Comment by d33pspace** [comment]
I agree. Thank you for catching this.

**Comment by elainetao829** [comment]
Reproducible on 2021-02-28.

**Comment by elainetao829** [comment]
Please remove the time range (the text highlighted in blue) from both the English and Chinese versions. We only need the text "Your giving history:" and the table. No time range or timestamp.

![image](https://user-images.githubusercontent.com/42002784/110647383-bee9e380-81f2-11eb-9d4f-c38c0d1d6ccd.png)

**Comment by elainetao829** [comment]
Verified successfully on 2021-03-11.
