### ISSUE TITLE
The layout of Donate page in English is not correct on a mobile phone.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#137]
Please see the comments for the expected behavior.

The layout for the highlighted part on the screenshot is not correct on Xiaomi MIX 2 (Resolution 2160x1080)

![image](https://user-images.githubusercontent.com/42002784/55543058-e24caf80-56fa-11e9-8cbf-f5073bf31d30.png)

**Comment by d33pspace** [comment]
Nice catch, thank you. This is worth correcting but assuming this is fully functional I don't want to mess with it now. I'm changing to paused status.

**Comment by elainetao829** [comment]
The problem is reproducible on 2021-02-28.

**Comment by elainetao829** [comment]
Expected Result:
Change the layout on both the website version and the mobile version, to below,

1. Remove the drop down list for selecting the donate frequency, but only leave the text: "I would like to make a gift of: "
2. Under the giving choices, but above the Donate button, add a checkbox with a text as this
[checkbox] I want my gift to repeat automatically every month.
See the draft here and hope it helps you understand better, the changes above are highlighted in red.
![Uploading image.png…]()

**Comment by elainetao829** [comment]
Verified successfully on 2021-03-13.
