### ISSUE TITLE
One error message is not translated on the Campaign Donate page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#141]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/56464690-90f22f00-6421-11e9-8e7f-47574770855a.png)

Expected Result:
The message should be translated as same as the donate page: 您的信用卡遭到拒绝。

**Comment by elainetao829** [comment]
For all card declined error, please use this error message for the English version:
Your card was declined. The error code is [xxxxx].
For the Chinese version, please use the error message below:
您的卡片被拒，错误代码为 [XXXX]。

**Comment by kolte** [comment]
@elainetao829 please review

**Comment by elainetao829** [comment]
Hi @kolte ,
Please change the error message into this,

For all card declined error, please use this error message for the English version:
Your card was declined. The error code is [xxxxx].
For the Chinese version, please use the error message below:
您的卡片被拒，错误代码为 [XXXX]。

Let me know if there is any question. Thanks!
Elaine

**Comment by elainetao829** [comment]
Test successfully on 2021-03-20
