### ISSUE TITLE
Rearrange address fields on user management details tab

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#15]
Please update the user management area details tab with the same configuration of address fields we use in the giving process. (1) City and State/Province on one line, (2) Postal code and country on one line, (3) State/Province fields reversed for Chinese language and placed above address fields.

![screenshot 97](https://user-images.githubusercontent.com/13606352/43983447-1e37dd54-9d2d-11e8-93ab-7c5587862da7.png)

![screenshot 101](https://user-images.githubusercontent.com/13606352/43983712-bbee2e6c-9d2e-11e8-8c3d-3ed332518c4e.png)

**Comment by kolte** [comment]
this is fixed, please review

**Comment by d33pspace** [comment]
@elainetao829 Please take a look at this when you can.

**Comment by elainetao829** [comment]
Hi,
The original problem has been fixed. But I noticed the orders of details in English and in Chinese are different. Is that on purpose:

![image](https://user-images.githubusercontent.com/42002784/44305298-d64bf180-a3a6-11e8-9823-a83668b4cdf6.png)

The order of Chinese is,

Name
Province       City
District/Street
Detailed Address
Zip                      Country

![image](https://user-images.githubusercontent.com/42002784/44305302-e06df000-a3a6-11e8-8618-3b68e4ee1611.png)

**Comment by kolte** [comment]
Yes, that is intentional, Jim @d33pspace  can confirm that.

**Comment by d33pspace** [comment]
@elainetao829 Hi, yes, this is intentional - wouldn't this make more sense to a Chinese person filling out an address form?

**Comment by d33pspace** [comment]
@elainetao829 Thanks, this is easy to fix. Let's do it!

@kolte Let's keep the country and postal code fields the same length, but on Chinese forms, place country above the City/State line and keep postal code where it is. This applies to the page mentioned here (user management) and also user detail entry upon making a gift.

**Comment by kolte** [comment]
@elainetao829 
![image](https://user-images.githubusercontent.com/8025877/44401386-1a3c2380-a56c-11e8-92a3-c4e99ca91a5e.png)

**Comment by elainetao829** [comment]
Sorry for jumping in. It's not ready for testing but I noticed the translation for ZIP CODE is not correct here.

It should be 邮编, instead of 压缩。

**Comment by d33pspace** [comment]
@elainetao829 I made the correction of 邮编。I also noticed somehow 姓名 was changed to 全名 and 县区、街道 was changed to 地址第1行 and 详细地址 was changed to 地址第2行. I prefer the previous translation in all cases. What do you prefer?

**Comment by elainetao829** [comment]
1. I agree the old translation is better. Please change 地址第一行 back to 县区、街道, and 地址第二行 back to 详细地址。 
省 is OK. We can leave it there.

2. The position of 国家 (country) is not correct. It should be placed under name but above 省 and 市.
![image](https://user-images.githubusercontent.com/42002784/44733335-f5baeb00-ab19-11e8-83a0-43089707ee8c.png)

**Comment by d33pspace** [comment]
Ok. I made these updates. Please give it a look and also confirm the address format and labels upon giving entry. There are four different files that contain that form! (First time gift from donation page, second+ gift from donation page, first time gift from campaign page, second+ gift from campaign page.)

**Comment by elainetao829** [comment]
The place of Country in Chinese is not correct. It should be placed under 姓名 (name) but above Province (省). 
![image](https://user-images.githubusercontent.com/42002784/44917284-8be55000-ad6a-11e8-9414-d23ba5b6f185.png)
![image](https://user-images.githubusercontent.com/42002784/44917304-9acc0280-ad6a-11e8-9f56-498fb46fc10f.png)

**Comment by d33pspace** [comment]
@elainetao829 I actually wonder if on Chinese pages, could we put both Country and Postal Code above Province? It's a little weird, but on Chinese envelopes the postal code also precedes the address. 

The advantage here is it would prevent us from having two lines only 1/2 full. But this is not a big deal at all.

**Comment by elainetao829** [comment]
@d33pspace the Zip code is always at the end in Chinese when people are writing an address. It has nothing to do with the envelop. 

However, as you said, it's not a big deal. You even can leave it as it's now.

**Comment by d33pspace** [comment]
@kolte For Chinese pages only, please make sure the Country field is below the Name field and above the State/Province field. The field will take up only 1/2 line. Also, please make sure it is the same length as the State/Province field below it. This should be true for all 4 payment pages and also the account management details tab.

**Comment by elainetao829** [comment]
Tested 4 donate scenarios and the user management page as well. Passed for all.
