### ISSUE TITLE
Invoice history page is messed up.

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#152]
Precondition: an account with no history in the last 12 months, but a history in the last 24 months
Click History tab, a PDF button appears (even before finishing loading)  click the PDF, 

Actual Result: after a few mins, the layout of the page is messed up

Expected Result: do not show the PDF button before finishing loading, and confirming there is a history for this account in the past 12 months

![issue](https://user-images.githubusercontent.com/13606352/82285081-26694500-99cd-11ea-83b3-c72509e324a2.png)

**Comment by elainetao829** [comment]
Reproduced on 2021-02-28.
![image](https://user-images.githubusercontent.com/42002784/109409496-35563c80-79ce-11eb-80a7-a9e3cc4b799a.png)

**Comment by elainetao829** [comment]
Hi @kolte ,
I still encounter this problem today. Could you please double check?
![image](https://user-images.githubusercontent.com/42002784/109963439-61075880-7d27-11eb-8a58-9cb509c5a3f8.png)

**Comment by elainetao829** [comment]
Verified successfully on 2021-03-10.
