### ISSUE TITLE
User is not able to sign up again successfully after unsubscribes. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#157]
Steps:
1. Use a new email address, to sign up for email communication on the home page.
2. Check in Drip. Click People, the new email is the first on the list. Open the email, it's marked as "Subscribed".
3. The mailbox receives the first email from Renewal. Unsubscribe through the link in the email.
4. Check in Drip again. Refresh the People page, the email is not the 1st anymore. Search for it in Drip, no result. 
5. Use the same email to sign up for email communication on the home page again.
6. Check in Drip again. 

Actual Result:
Still no result. It means the re-subscription does not work.

Expected Result:
The re-subscription works and the email can be found in Drip again with the status subscribed.

To do:
Drip allows people to unsubscribe with an opt-in form under (any) campaign. 
1. We can create an embedded form under the welcome campaign and embed the codes into our website.
2. If the website is displayed in English, we must use the English welcome campaign (https://www.getdrip.com/7811515/campaigns/881020560), and the Chinese welcome campaign (https://www.getdrip.com/7811515/campaigns/255753008) if the website is in Chinese.
3. We shall not enable ReCaptcha when designing the form because it's not accessible in China.

**Comment by kolte** [comment]
Hi @elainetao829 ,
I have tried given steps and found that during the mail send process it is failing at step #14 in Zappier due to rule set to check username already exist. I think that rule maybe need to remove as in case of resubscription user will always already existing. Please find attached screenshot.
![image](https://user-images.githubusercontent.com/8025877/126169181-9e094ff0-b23b-4a06-a421-09ed67f043c3.png)

**Comment by elainetao829** [comment]
Hi @kolte ,
I think your screenshot was from this zapier: Website email subscription submission, correct? But at the 11th step of this zapier, this person is already subscribed to Drip, while we can't search him/her out in drip at all. Isn't it strange?
What about the drip opt in form? Could that be a solution for this ticket?

**Comment by elainetao829** [comment]
Close the ticket as the problem is already fixed by Jimmy.
