### ISSUE TITLE
Drip Snippet is not working properly on our website.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#159]
The Drip Snippet is not working properly, not sure if we ever installed it correctly.
Please check the instructions on Drip if necessary: https://my.drip.com/docs/guides/install-your-javascript-snippet

**Comment by elainetao829** [comment]
![image](https://user-images.githubusercontent.com/42002784/111114202-de3f9280-859d-11eb-97fb-2c35bb886996.png)
Verified successfully on 2021-03-15

**Comment by elainetao829** [comment]
Get drip code is not on the news page. @kolte can you please take a look?

**Comment by kolte** [comment]
Hi @elainetao829 ,
drip mail code in partial view, I have checked email subscription on Home,Services & News page its working, i am getting emails for subscription.

**Comment by elainetao829** [comment]
![image](https://user-images.githubusercontent.com/42002784/126341483-3f17e727-504e-45ee-a460-65b8c61ed0ce.png)
getdrip is also on the news page now. Close this ticket.
