### ISSUE TITLE
Allow users to update email and salutation on email preference update page

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#16]
Add an email field and a salutation (first name) field to the email preference update page. Note that the salutation will be sent to the page through the URL like so: /preference?email=jimmy.mcw@live.com&salutation=Jimmy

Send the new email value and salutation to Zapier upon form submit.

![screenshot 99 _li](https://user-images.githubusercontent.com/13606352/43983794-4148fa74-9d2f-11e8-8e98-0234037f71d2.jpg)

**Comment by kolte** [comment]
this is fixed, zappier test is pending, will need zappier account access to test

**Comment by d33pspace** [comment]
@elainetao829 Please take a look at Girish's work so far on this. I'll handle the Zapier (back-end) testing later.

**Comment by d33pspace** [comment]
This is looking great to me can confirm that the backend is receiving the data. @elainetao829 Your input please, and we need the correct translation for "Select your communications preferences and submit to confirm." (or is that line even necessary?)

**Comment by elainetao829** [comment]
Verified and confirm the functionality works fine.

For the translation, you can use 请选择您的偏好并提交。But I would say it's even better to remove this line (for both Chinese and English）. It's not so meaningful...

**Comment by d33pspace** [comment]
Hi @kolte. I've removed the unnecessary instructions from this page but now there is not enough space between the heading and body. Take a look at the screenshot below:

![screenshot 176 _li](https://user-images.githubusercontent.com/13606352/44783591-6a933100-abbd-11e8-9e53-3816fbfabde8.jpg)

**Comment by d33pspace** [comment]
Looks great!
