### ISSUE TITLE
High severity security vulnerability alert from Github.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#162]
We received an email from Github regarding a high severity security vulnerability. 
![image](https://user-images.githubusercontent.com/42002784/114204300-9e48b100-998b-11eb-9d74-1a8a4907d5ab.png)
full details may be here: https://github.com/advisories/GHSA-52p9-v744-mwjj

**Comment by kolte** [comment]
Manually updated package versions to resolve this issue

**Comment by elainetao829** [comment]
Close the ticket for now.
