### ISSUE TITLE
Trying to make the payment through a strip test card, an unhandled exception occurred.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#167]
1. Open the donate page.
2. Select a donate option and enter the card number 4000008260003178, and other mandatory fields.
3. Click Submit Payment button.

Actual Result:
An unhandled exception occurred.
![Actual Result PNG](https://user-images.githubusercontent.com/42002784/122952549-a58b3280-d3b0-11eb-8e2c-9b2f68257fa0.png)

Expected Result:
The card should lead to a decline scenario, according to Stripe: his card requires authentication for one-time payments. All payments will be declined with an insufficient_funds failure code even after being successfully authenticated or previously set up.
The system should catch the error.

**Comment by kolte** [comment]
Hi @elainetao829 ,
Object reference Issue resolved in case of card declined & repayment. now it will show card declined related message.

**Comment by elainetao829** [comment]
Test passed.
![image](https://user-images.githubusercontent.com/42002784/126341002-585b90ff-43a8-4823-ad5d-03c743e15841.png)
