### ISSUE TITLE
User clicks Search button (on History page) and clicks PDF, the Search button will be disabled forever.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#17]
Steps:
1. User opens History tab of Account Management.
2. User clicks Search button. 
3. Before the system finishes searching, User clicks PDF. The system asks User to Save or to Open the PDF.
4. User selects Cancel.
5. User checks the Search button.

Actual Result:
The Search button is disabled still, and will not be enabled unless user refreshes the page.

Expected Result:
The Search button will not be disabled forever.

**Comment by elainetao829** [comment]
I think this is introduced while fixing https://github.com/d33pspace/RenewalWebsite/issues/8.

**Comment by d33pspace** [comment]
Hi Elaine, I wasn't able to reproduce this. Is it happening only in Firefox or all browsers? Can you please try some more scenarios and add some detail?

**Comment by elainetao829** [comment]
[Disabled Search Button.ZIP](https://github.com/d33pspace/RenewalWebsite/files/2289122/Disabled.Search.Button.ZIP)
@d33pspace  I recorded my screen. Hope this could help a little.

**Comment by d33pspace** [comment]
Argh. Sorry Elaine, you may be using a ZIP format I don't have? Maybe try uploading an mp4 directly?

**Comment by elainetao829** [comment]
@d33pspace it's a ZIP as GitHub requires. The video is an exe format. You only need to download it and unzipped. The exe can be played then.

If you don't have the unzip tool, I think you just need to change the file name into rar or 7z. It should work. Let me know if it's not.

**Comment by d33pspace** [comment]
No worries. I'd rather not install support for RAR on this machine. Let's try to stick with steps and screenshots. Let me experiment further myself with this one.

**Comment by d33pspace** [comment]
I'm closing this for now. We can address it in issue #24.
