### ISSUE TITLE
Sometimes switching between different tabs in the account management module is not possible.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#172]
Steps:
1. Log in.
2. Click the email address on top right to open the account management module.
3. Switch between different tabs.

Actual Result:
Sometimes switching is not working. Please check the video for more details

https://user-images.githubusercontent.com/42002784/152716924-65d49988-b8c4-4ae2-b331-d7d462873ec0.mp4

.

**Comment by d33pspace** [comment]
@kolte 
Could you please take a look at this?

**Comment by elainetao829** [comment]
The problem is fixed.
