### ISSUE TITLE
The message "please select a country" should be in Chinese while user selects the language as Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#18]
Steps:
1. User opens Account management page in Chinese.
2. User opens tab Details (个人资料).
3. User opens the dropdown list of Country and checks the first line.

Expected Result:
There would be a Chinese message/hint: 请选择一个国家

Actual Result:
The message is in English: please select a country.
![image](https://user-images.githubusercontent.com/42002784/44038970-97c4c898-9f4a-11e8-9da5-dc9515757627.png)

**Comment by d33pspace** [comment]
This should be corrected now, please take a look.

**Comment by elainetao829** [comment]
Verified and passed.
