### ISSUE TITLE
The wordings on the Subscription Preference page need to be updated.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#20]
Steps:
1. User subscribes Renewal with a real email.
2. User clicks the Change Language button in the subscription email.
3. User checks the wordings on the page. 

Expected Result:
1. In Chinese, the ellipsis should be …… instead of 。。。
2. The language options below should be 
简体中文  (this needs to be Chinese forever, so that Chinese users can understand)
English (this needs to be English forever)

![image](https://user-images.githubusercontent.com/42002784/44041788-311ddad8-9f51-11e8-8ea0-9114e49db113.png)

**Comment by d33pspace** [comment]
Ready for your review.

**Comment by elainetao829** [comment]
@d33pspace  this is on the PROD too. Please update or deploy accordingly.

**Comment by elainetao829** [comment]
It's still not changed in staging even (I cleared cache already).
![image](https://user-images.githubusercontent.com/42002784/44151048-f057f1ee-a0d3-11e8-93f9-42bfaac8b8a0.png)

**Comment by elainetao829** [comment]
Verified and confirm the ellipsis bug has been fixed.

For the language bug, it's a little bit weird now. I think no matter user is at an English page or a Chinese page the two options will always be,
简体中文
English

Just as the language on the top right corner, Chinese is always 中文, for Chinese users to understand and select. See the picture below

![image](https://user-images.githubusercontent.com/42002784/44151674-d8874b76-a0d5-11e8-8fb8-a93aca08481b.png)

**Comment by d33pspace** [comment]
Good thinking, thanks. This was actually incorrectly implemented for Chinese language selection and I've made the correction.

**Comment by d33pspace** [comment]
I am closing this as we can continue discussion in issue #16.
