### ISSUE TITLE
The Chinese translation for Home is not correct on contact thank you page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#21]
Expected Result:
主页

Actual Result:
家

![image](https://user-images.githubusercontent.com/42002784/44042191-405f9666-9f52-11e8-9048-214316ed4809.png)

**Comment by elainetao829** [comment]
@d33pspace I just noticed the bug I reported is on the PROD, not staging. Because the url in the subscription email leads to the PROD directly. Please update the PROD code for this bug.

**Comment by d33pspace** [comment]
@elainetao829 Ah. Yes, you are correct. For this type you can change the URL to test on staging. At this point you only need to test on staging (except for things that can only be tested on PROD) so go ahead and close these issues once they are correct on staging. Thanks!

**Comment by elainetao829** [comment]
It's still not correct in the staging even (I cleared cache again).

**Comment by elainetao829** [comment]
![1](https://user-images.githubusercontent.com/42002784/44150949-b5beba7c-a0d3-11e8-8c0e-8281c022138b.png)

**Comment by elainetao829** [comment]
Verified again and realized my url was not correct. It's OK now. The bug has been fixed.
