### ISSUE TITLE
“Please select a country" shoud not be able to be selected.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#22]
Steps:
1. User opens account management page.
2. User opens tab Details.
3. User opens the dropdown list of Country, and tries to select and save the 1st option: Please select a country.

Actual Result:
It can be selected and even saved successfully.

Expected Result:
It should rather be a hint/message than a real option, i.e. it should not be able to be selected and saved.

![image](https://user-images.githubusercontent.com/42002784/44152861-27fa80a8-a0d9-11e8-99c7-bb94dc41f5ec.png)

**Comment by d33pspace** [comment]
I agree this is strange. Can you please compare this to another site and further explain what normal behavior should be expected from this type of control? For example, what if the user desires to remove the country data without selecting another country? Should there also be an option for "(No selection)"?

**Comment by elainetao829** [comment]
I checked Amazon and Paypal.

For Amazon, there is no blank option or option like "please select a country". It's defaulted as China (I think it takes my IP address). I'm able to select another country. But I'm not able to remove the value to empty.

For Paypal, the country is defaulted too and I cannot change it even. But for Province, it's similar as ours. It as an option called "Province"

**Comment by kolte** [comment]
I think we should keep it simple, if it's optional then let's just keep the text "Please select country" and if user want to select he/she will select or ignore it.

We can do the default country selected and other option if this field is required if not then it's good as it is now.

@d33pspace @elainetao829

**Comment by d33pspace** [comment]
@kolte I agree. But please go ahead and make China the default selection when CurrencySettings:ServerLocation = "China". For "USA" there is no default selection.

**Comment by d33pspace** [comment]
I found a solution I like! Please see the dropdown list in the screenshot below. The top option is simply blank. So let's remove the phrase "Please select country" and just have that blank. And it should be selectable in case the user would like to save the field without a value. @kolte Please update the (4) payment views and the account management details tab accordingly.

![dropdown](https://user-images.githubusercontent.com/13606352/45192978-5b2b7c00-b27e-11e8-874c-0b5fc737ba25.png)

**Comment by elainetao829** [comment]
Verified and confirm fixed.
