### ISSUE TITLE
On invoice history, remove date search in favor of buttons

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#24]
Steps:
1. User opens account management page.
2. User opens tab History.
3. User selects the dash between month and date.
4. User hits the backspace key on the keyboard.
5. User tries to enter a correct date.

Expected Result:
User is able to enter a correct date.

Actual Result:
User is not able to enter a correct date unless he refreshes the page. 

Please see the screen recording here for more information.
[Cant enter a correct date.zip](https://github.com/d33pspace/RenewalWebsite/files/2290536/Cant.enter.a.correct.date.zip)

**Comment by d33pspace** [comment]
I've also noticed some abnormalities with date entry. Will you please try posting the original mp4 instead of the ZIP file, and also please test date entry in several browsers, Android and iOS so we can make sure to get this problem solved completely. I've also wondered about not allowing date entry but just allowing options like, "This year" "Last year" "Entire history" . . . what do you think?

**Comment by d33pspace** [comment]
@kolte I'd like to remove the date controls on the invoice history search and just have four buttons instead: "Last 12 months" (default) "Last year" "This year" and "All history". The dates displayed on the PDF report will not change. See screenshot below.

![screenshot 156 _li](https://user-images.githubusercontent.com/13606352/44381525-48f1d400-a543-11e8-9009-1688b12c2995.jpg)

**Comment by elainetao829** [comment]
Verified and I think this is not correct.

1. I see Jimmy mentioned only "remove the date button". What about the PDF button? Do we still need it? When should it appear (the PDF will only come out if there is history found)?

2. Currently there is no PDF button any more. User clicks a button, e.g. this year. if there is any record found, the system will ask user to save or open the PDF. Please be kindly noted, for this implementation, the history table below on this page has also been removed.

3. Now if there is no history, the error message is different from the past. And it's not a correct error message to me. Why we are changing this?

![image](https://user-images.githubusercontent.com/42002784/44533654-99765680-a728-11e8-8489-535e7844eb1b.png)

**Comment by elainetao829** [comment]
Also I noticed the date format in the Chinese PDF has been modified somehow.

![image](https://user-images.githubusercontent.com/42002784/44534028-6da7a080-a729-11e8-8ca5-ee64f4bbd4f6.png)

Please change the format to YYYY-MM-DD, such as 2017-01-01 至 2018-01-01

**Comment by d33pspace** [comment]
Continuing the conversation in issues #60 and #61.
