### ISSUE TITLE
The 3rd party log in page is not translated into Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#26]
Steps:
1. Open log in page.
2. Click a 3rd party, e.g. Google.
3. Enter in Google account and the system will come back to Renewal 3rd part log in page.
4. Click the 中文 (Chinese) button on top right.

Expected Result:
Everything on the page would be Chinese.

Actual Result:
The wordings are all English.

Register.
Associate your Google account.
Association Form

注册
关联您的Google账户  (or Facebook or ...)
关联形式

You've successfully authenticated with Google. Please enter an email address for this site below and click the Register button to finish logging in. 
您已经成功通过Google的验证。请在下方输入一个邮件地址，然后点击注册按钮，完成登录。

RIGSTER
注册

![image](https://user-images.githubusercontent.com/42002784/44202023-6a3a7500-a17d-11e8-954e-235e628287e2.png)

**Comment by elainetao829** [comment]
Log in failure page is also in English only.

![image](https://user-images.githubusercontent.com/42002784/44202117-a53ca880-a17d-11e8-9ad1-a2970bcdcaea.png)


Login Failure.
登录失败

Unsuccessful login with service.
登录服务不成功

**Comment by d33pspace** [comment]
@elainetao829 Give this a try now, and let me know if you have any trouble with repeated testing of external login.

**Comment by elainetao829** [comment]
@d33pspace I verified and confirm the 1st has been fixed correctly. For the login failure message, I couldn't reproduce it. Do you have any suggestion?

**Comment by d33pspace** [comment]
@elainetao829 Could you please test the change so far and advise re how to reproduce the login failure message?

**Comment by elainetao829** [comment]
Sorry @d33pspace  I tried and I couldn't reproduce the log in error now. I would close this ticket for now and open a new one once I reproduce it.
