### ISSUE TITLE
Logging in with Facebook account fails. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#28]
Steps:
1. Open the log in page of the PROD.
2. Select log in with Facebook.

Expected Result:
Log in successfully

Actual Result:
Log in failed on Facebook.

The Chinese error message says: The application has not been configured: the application is still in the development mode. You don't have the access. Please switch to a registered account, or ask the admin for permission.

![image](https://user-images.githubusercontent.com/42002784/44245091-ab786680-a209-11e8-94ef-172442ccc4ac.png)

**Comment by elainetao829** [comment]
I'm raising this as a question because I think maybe Facebook now is available for some certain accounts only? @d33pspace can you provide a test account for me?

**Comment by d33pspace** [comment]
Please try this again on staging.

**Comment by elainetao829** [comment]
Verified in staging and passed.
