### ISSUE TITLE
Cancelling the access to Microsoft accounts leads to an unhandled exception.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#29]
Steps:
1. Open log in page of the PROD website.
2. Select to log in with Microsoft.
3. Enter in Microsoft password and account, and click log in.
4. Click Cancel when the system asks user to confirm Permissions requested.

Actual Result:
An unhandled exception comes out.

![image](https://user-images.githubusercontent.com/42002784/44245354-d1ead180-a20a-11e8-9a64-c1218e91db07.png)

![image](https://user-images.githubusercontent.com/42002784/44245371-e333de00-a20a-11e8-9426-f6030895e160.png)

**Comment by d33pspace** [comment]
@kolte Could you please check this out? Seems like we should just redirect to the account sign in page in this case.

**Comment by elainetao829** [comment]
Hi @d33pspace,
I couldn't reproduce this bug as the permission requested dialog does not come out again. I guess this is because I have granted permission before. Can you please remove my Microsoft account completely for FAT or PROD so that I can try again?

**Comment by d33pspace** [comment]
@elainetao829 Regarding your comment above, the dialogue with the Microsoft logo in the screenshot above is of course under Microsoft's control, but the error message "And unhandled exception..." is ours.

**Comment by elainetao829** [comment]
Hi, 
I couldn't reproduce this. I'm closing this for now.
