### ISSUE TITLE
After log in with Microsoft account successfully, user even clicks "create a new account" will log in with the old account.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#30]
Steps:
1. Open the log in page of the PROD website.
2. Select log in with Microsoft.
3. Enter in Microsoft account and password and grant the permission.
4. After log in successfully with Microsoft account, click Log out.
5. Click log in with Microsoft again.
6. Select use another account on the Microsoft page, instead of selecting the old one(s) (I have two Microsoft accounts so the system asks me to select one).
7. Click Create One (account).
![image](https://user-images.githubusercontent.com/42002784/44245741-e334dd80-a20c-11e8-87dc-1445dcc22d8d.png)

Expected Result:
The system would open a create new account page.

Actual Result:
Logged in with the old account again (same as step 3).

Please confirm it's a Renewal bug or a Microsoft bug...

**Comment by d33pspace** [comment]
@elainetao829 Interesting. I don't think there's anything we can do about this one. Go ahead and close this once you read this message.
