### ISSUE TITLE
Questions/requirements about logging in with external account.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#31]
Hi Jimmy,

I have some questions regarding the functionality and requirement of logging in with external account. Please help me with them and I would raise defect or enhancement for some after your confirmation.

1. Is it possible to change the external account after log in once successfully?
User logs in with one Google account successfully --> User logs out --> User clicks log in with Google again --> User logs in with the old account directly 
There is no way/option for user to select whether he/she wants to use the old Google account or a new one. Is this on purpose?

2. What's the reason we ask user to enter an email manually after getting the authorization from the external account.
User clicks log in with Google/Microsoft for the 1st time --> The system would open Google's website and tries to get authorization from Google -->User enters in correct Google account and password, and confirms the authorization --> The system would go back to Renewal and asks user to enter an email to finish the log in --> User is able to enter any other email account in the field

Since user has already selected log in with Google/Microsoft, why we don't use the account directly but ask user to manually enter one? And if user enters a different email, but actually he/she is using Google/Microsoft account, would that be weird?

**Comment by d33pspace** [comment]
(1) In the user management area, under the Password tab, there is a button for managing connected accounts. Does this answer your question here? 

![screenshot 159](https://user-images.githubusercontent.com/13606352/44384181-ea7e2300-a54d-11e8-8037-2d996b7165da.png)

(2) Yes, this is a little strange and is related with the package we are using to accomplish external authentication. Users must still enter an email the first time when using external login, but it is fine for users to, say, sign in with Google, and enter a non-Google email address.

**Comment by elainetao829** [comment]
Thanks for answering my questions. They make sense to me so I'm closing this ticket.
