### ISSUE TITLE
The arrow on the dropdown list is missing when using IE or Edge.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#32]
The arrow on the dropdown list field is missing, on the donate page.

![image](https://user-images.githubusercontent.com/42002784/44246352-686dc180-a210-11e8-8c1f-a324d2f15da9.png)

**Comment by d33pspace** [comment]
Hi @elainetao829 let's discuss this. I don't like the solution Girish implemented here, in Edge it comes across with ugly grey and blue (see my screenshot below). It also looks disabled by default. 

I'm thinking actually the default way this control renders in IE/Edge has no drop-down arrow, and it may be best to keep it like that. But if you think it could be confusing to the user, you might browse around and find a control you like we could advise Girish to copy.

![screenshot 168](https://user-images.githubusercontent.com/13606352/44613693-eaca3700-a849-11e8-9cf7-2f3ffd626776.png)

**Comment by elainetao829** [comment]
@d33pspace I just checked Amazon and it's using the same pattern as we are now.
![image](https://user-images.githubusercontent.com/42002784/44763696-ecb03500-ab7e-11e8-809c-e26bd5466c4b.png)

Let me check some more examples later and see if we can find a better solution.

**Comment by elainetao829** [comment]
@d33pspace I just found a little bit weird behavior of the dropdown list: if user opens the dropdown list (by clicking the arrow) and scroll down/up the page, the dropdown list will also be moved up/down. This happens to Edge only.

**Comment by elainetao829** [comment]
![1](https://user-images.githubusercontent.com/42002784/44795963-8529d200-abde-11e8-919f-bea57f497f4c.png)

**Comment by d33pspace** [comment]
@kolte Can you comment on the odd list box behavior Elaine mentioned above in Edge? If this is a bug in Edge we will not mess with it but if there is an easy solution let's implement it.

Also, the list box is now different on https://staging.renewal365.org/donate and https://staging.renewal365.org/donate/campaign Please make sure both pages use the preferred style.

**Comment by elainetao829** [comment]
The dropdown list is not moving to down and up now. Confirm it's fixed.
Also the styles of Campaign page and Donate page are the same now.
