### ISSUE TITLE
The message format on the card verification page needs to be adjusted.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#33]
Actual Result:
The address at which you'd like to receive Renewal communications(optional,not related with card verification)

Expected Result:
The space is missing.

The address at which you'd like to receive Renewal communications (optional, not related with card verification)

![image](https://user-images.githubusercontent.com/42002784/44246763-889e8000-a212-11e8-8ac0-b4cc7f497cb2.png)

**Comment by d33pspace** [comment]
Let's address this in issue #14 - @elainetao829 Please close this issue once you read this message because I want to make sure this is addressed.

**Comment by elainetao829** [comment]
Thanks for notifying. I'm closing this now and will keep testing and verifying this in issue #14
