### ISSUE TITLE
The subscription cancellation confirm dialog should be in Chinese when user sets the language as Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#35]
Precondition:
User subscribed a donate before.

Steps:
1. User opens account management.
2. User opens tab Subscription.
3. User sets the language on the top right as Chinese.
4. User clicks the Cancel button after the subscription.

Actual Result:
Only part of the dialog is translated into Chinese.
![image](https://user-images.githubusercontent.com/42002784/44305030-1fe50e00-a3a0-11e8-8c42-50aaad883138.png)

Expected Result:
warning should be 警告
CONFIRM should be 确认
CANCEL should be 取消

Also some attributes in the table are not translated.
Monthly  --> 每月 (Please also translate Quarterly as 每季 and Yearly as 每年 here)
Active --> 有效

**Comment by d33pspace** [comment]
@kolte Is it possible to use a standard browser dialogue here instead of a custom pop-up? For the English, let's remove the word "Warning" and just use, "Are you sure you want to cancel this subscription?" Then implement Elaine's translation as indicated.

**Comment by d33pspace** [comment]
@kolte Sure. Just let us know when you've made the text change and translation fix and we'll go from there.

**Comment by kolte** [comment]
this is fixed, please check

**Comment by elainetao829** [comment]
Verified and confirm fixed.
