### ISSUE TITLE
Security Code (of credit card) is not tranlsated into Chinese correctly.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#37]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/44305452-eb764f80-a3a9-11e8-9ea3-1d29be24cf4d.png)

Expected Result:
安全码

**Comment by d33pspace** [comment]
Corrected, please check after 10a today.

**Comment by elainetao829** [comment]
Verified and fixed.
