### ISSUE TITLE
The log in error message is not tranlsated into Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#38]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/44344573-a0e8f600-a4c3-11e8-851e-dc1d767d6457.png)

Expected Result:
    The Email field is not a valid e-mail address.
 无效的邮箱地址

    The Password field is required.
请输入密码

**Comment by d33pspace** [comment]
@kolte I couldn't find these messages to translate. Could you please find them and implement the translation Elaine has suggested?

**Comment by kolte** [comment]
@d33pspace sure

**Comment by d33pspace** [comment]
Translation needed here: 
The Email field is not a valid e-mail address. = 无效的邮箱地址
The Password field is required. = 请输入密码

![screenshot 160 _li](https://user-images.githubusercontent.com/13606352/44433300-54dba580-a5d8-11e8-90d3-aa798e4e7535.jpg)

**Comment by elainetao829** [comment]
Verified and confirm fixed.
