### ISSUE TITLE
The Chinese tranlsation on the PDF is not correct.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#39]
There are two phrases need to be replaced by 日新中心. See the two phrases highlighted below. 

![image](https://user-images.githubusercontent.com/42002784/44345771-d3482280-a4c6-11e8-8cde-8088080104db.png)

**Comment by d33pspace** [comment]
Thanks. Corrected. Please check on this today after 10 a.m.

**Comment by elainetao829** [comment]
@d33pspace Verified and it was fixed.
And I just noticed the name of the PDF file is in English. Do you also want to translate that?

It should be 日新中心捐赠记录

**Comment by d33pspace** [comment]
@kolte Please change the PDF file name to 日新中心捐赠记录 for Chinese language selection.

**Comment by kolte** [comment]
@d33pspace ok

**Comment by d33pspace** [comment]
@kolte I'm not sure what you changed here. The typical filename of the PDF is "Renewal giving record.pdf". We'd like it to be "日新中心捐赠记录.pdf" when Chinese language is selected.

**Comment by d33pspace** [comment]
@elainetao829 Please check on this one.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
