### ISSUE TITLE
Adding another service to log in leads to 404.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#42]
Steps:
1. User logs in with Google.
2. User opens user management page.
3. User opens tab Password.
4. User clicks Manage (External Logins).
5. User clicks Google/Facebook/Microsoft under Add another service to log in.

Expected Result:
User is able to add other external login accounts.

Actual Result:
404 not found.

![image](https://user-images.githubusercontent.com/42002784/44409371-d9a4d000-a594-11e8-8a50-e926804c7d4d.png)

**Comment by d33pspace** [comment]
@kolte Could you please take a look at this? This seems to be something that should work out of the box, but perhaps something was not updated to .NET 2.0. Also note that it doesn't really matter to me that users are able to sign in using multiple services, but it seems that they should be able to disassociate and add another.

**Comment by elainetao829** [comment]
Adding a facebook account while logged in with Google still causes error as below,

![image](https://user-images.githubusercontent.com/42002784/45303942-92817d80-b549-11e8-9b23-5961dc7912c8.png)

The 404 error has been fixed though.

**Comment by d33pspace** [comment]
I'm closing this as it will be covered under #103
