### ISSUE TITLE
The 404 page is not translated into Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#43]
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/44409504-06f17e00-a595-11e8-8b95-d5f87387dfeb.png)

Expected Result:
404 Page Not Found
404页面无法找到

Sorry, an error has occured, Requested page not found!
抱歉，出现了一个错误。您请求的页面没有找到！

BACK HOME
返回主页

Also, @d33pspace could you please confirm if "occured" above should be "occurred" from a native speaker point of view?

**Comment by d33pspace** [comment]
English and Chinese updated.

**Comment by elainetao829** [comment]
Verified and fixed.
