### ISSUE TITLE
The error message on forgotpassword page is not translated into Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#45]
Actual Result:
Entering a wrong email address:
![image](https://user-images.githubusercontent.com/42002784/44469684-9f056b00-a65a-11e8-9fd8-9d06dfa46049.png)

Entering nothing:
![image](https://user-images.githubusercontent.com/42002784/44469771-cbb98280-a65a-11e8-8227-6247e5be6001.png)

Expected Result:
The Email field is not a valid e-mail address.
 您输入的邮箱无效。

    The Email field is required.
请输入邮箱。

**Comment by elainetao829** [comment]
Also, I think the error message under the email field and above that are a little bit duplicated. What's your idea?

**Comment by d33pspace** [comment]
@kolte Could you make this change, please?

@elainetao829 I agree the error messages are a bit redundant but this is part of packaged functionality so I think it's best to mess with it as little as possible.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
