### ISSUE TITLE
The Chinese translation on the log in page needs to be updated.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#46]
Actual Result:
When user does not enter any email address
![image](https://user-images.githubusercontent.com/42002784/44470166-9e210900-a65b-11e8-896b-aead9b90c9d4.png)
The error message is 电子邮件字段是必需的。

Expected Result:
请输入邮箱。

**Comment by d33pspace** [comment]
@kolte Could you make this change, please?

**Comment by elainetao829** [comment]
Verified and confirm fixed.
