### ISSUE TITLE
Set the language as Chinese and ask the website to reset password, the email is still in English.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#47]
Steps:
1. User sets the language of the website as Chinese.
2. User opens log in page.
3. User clicks forget password.
4. User enters an email address.
5. User checks the reset password email in the mailbox.

Expected Result:
The language of the email would be in Chinese.

Actual Result:
The language of the email is in English.

@d33pspace do you have a translated email here in Chinese? Or do you want me to do the translation?

**Comment by d33pspace** [comment]
@kolte Can you please first implement a Google translation of the Chinese password reset email, then @elainetao829 will provide proper translation.

@elainetao829 If you have time you could also first provide the translation here. We don't have a translation for that yet. Thank you.

**Comment by elainetao829** [comment]
Hi @kolte 
Please remove the “你好” before user's name. This is reductant. 
![image](https://user-images.githubusercontent.com/42002784/44786958-57399300-abc8-11e8-929c-8241812359ee.png)

**Comment by d33pspace** [comment]
@kolte In addition to Elaine's correction above, please remove the grey box header and simply replace with `<img src="https://www.renewal.org.cn/images/renewal-logo@2x.png" width="125" />` and also use our custom HTML button format for the button: 

`<table cellpadding="12" cellspacing="0">
	<tbody>
		<tr>
			<td align="center" bgcolor="#d11241" style="-webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; color: #ffffff; display: block;"><a href="https://www.renewal.org.cn/donate" style=" font-weight: bold; text-decoration: none; text-transform: uppercase; width:100%; display:inline-block"><span style="color: #FFFFFF">Reset your password</span></a></td>
		</tr>
	</tbody>
</table>`

**Comment by d33pspace** [comment]
@elainetao829 I believe you can continue on this one since we've resolved #87 :)

**Comment by elainetao829** [comment]
HI @d33pspace 
It has been a long ticket. The original problem has been solved. I would close this and open a new one.
