### ISSUE TITLE
Reset Password page is not completely tranlsated into Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#48]
Steps:
1. User clicks forget password and enters an email address.
2. User receives the reset password email and clicks the link. The system would open a reset password page.
3. User sets the language as Chinese and check.

Actual Result:
The phrases "Reset Password" and "Reset your password" are not translated into Chinese.
![image](https://user-images.githubusercontent.com/42002784/44471094-c4e03f00-a65d-11e8-8b16-68f657fb1865.png)

Expected Result:
Reset Password. should be 重置密码

Reset your password. should be 请重置您的密码。

**Comment by elainetao829** [comment]
It would be even better to remove the period "." in the title and change it to Register Password (capital). It's a title instead of a sentence.

See the titles of other pages for your reference.
https://staging.renewal365.org/account/login
https://staging.renewal365.org/account/register

**Comment by d33pspace** [comment]
@kolte Please take care of this if you can, and I agree please remove the period that @elainetao829  suggested.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
