### ISSUE TITLE
The wording and translation of Register and Reset Password pages.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#49]
For English,

Actual Result:

Register
![image](https://user-images.githubusercontent.com/42002784/44471486-9ca51000-a65e-11e8-9095-7ba81174149a.png)

Reset Password
![image](https://user-images.githubusercontent.com/42002784/44471558-bf372900-a65e-11e8-9ec6-1c466eebbfb3.png)

Expected Result:
Reset Password page should be the same as Register, i.e., the last password should be Confirm Password (please change the corresponding Chinese word to the same as the one on Register, which is 确认密码）

**Comment by elainetao829** [comment]
For translation,
Actual Result:
The error messages on both pages are the same, and are both not translated.
![image](https://user-images.githubusercontent.com/42002784/44471805-44bad900-a65f-11e8-94c5-c1ad6919f547.png)

Expected Result:
The Email field is required. --> 请输入邮箱。
The Password field is required. --> 请输入密码。
 The Email field is not a valid e-mail address.  -->无效的邮箱地址。
 The Password must be at least 6 and at max 100 characters long.  --> 密码长度必须在6--100个字符之间。
 The password and confirmation password do not match.  --> 两次输入的密码不一致。

**Comment by d33pspace** [comment]
@kolte I'll be happy to do this when I have time but please take care of this first if you can.

**Comment by elainetao829** [comment]
Confirm fixed.
