### ISSUE TITLE
Reset Password Confirmation page is not translated into Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#50]
Actual Result:

Reset password confirmation.

Your password has been reset. Please Click here to log in.

![image](https://user-images.githubusercontent.com/42002784/44472210-48029480-a660-11e8-8e3a-b4401d22ac35.png)

Expected Result:

For English, Reset password confirmation. should remove the period and change into
Reset Password Confirmation 

For translation,
Reset password confirmation. --> 重置密码确认
Your password has been reset. Please Click here to log in.  --> 您的密码已被重置。请_点击此处登录_。

**Comment by d33pspace** [comment]
@kolte I'll try to get to this if I can but I'd appreciate if you could handle this.

**Comment by elainetao829** [comment]
Confirm the translation is fixed.

And the period is removed. Thanks @kolte I'm too picky sometimes :)
