### ISSUE TITLE
The reset password workflow is not right.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#51]
Steps:
1. User clicks forget password on log in page.
2. User enters an email to reset the password.
3. User receives the reset password email in the mailbox he/she entered in step 2.
4. User clicks the link in the email to reset password.

Actual Result:
User is able to enter any email address on the reset page. 
He/she can enter an invalid email address (never registered) and the system let the user reset password successfully. 

Expected Result:
Entering an invalid email address should be prohibited.

**Comment by d33pspace** [comment]
@kolte Can you check this out, please? This is strange. Since this function is packaged with .NET Core it seems like there should be a solution or setting that needs to be tweaked.

**Comment by d33pspace** [comment]
@elainetao829 I'm sorry I just want to confirm this is not a feature to allow the user to change their email address. For example, if a user enters a new email address is the user able to now sign in under the newly entered email address and not the old one?

**Comment by elainetao829** [comment]
Hi @d33pspace ,

Here is the reset password page.

![image](https://user-images.githubusercontent.com/42002784/44918697-37dc6a80-ad6e-11e8-8908-5c9a362f6728.png)

The email field is for user manually entered. User is able to enter an email that never existed in the system and enter passwords for that. The system would say the password has been reset successfully. However, user is not able to log in with the new email and password. 

I would say the basic logic and functionality are correct, though not perfect. If it's something we need to spend much time on that to fix, I think we can leave it as it's now.
