### ISSUE TITLE
why not move this in the data folder + all context invoking classes

### ISSUE THREAD

**Issue by jmurekezi** [d33pspace/RenewalWebsite#53]
https://github.com/d33pspace/RenewalWebsite/blob/1accf46d2d328eabbfd5fe2d738733a754f5affa/RenewalWebsite/CountrySeeder.cs#L10

**Comment by d33pspace** [comment]
@kolte Your thoughts on this please?

**Comment by d33pspace** [comment]
@kolte It does make sense to me that this be in the data folder. Also wondering about EmailNotification and EmailSettings.

**Comment by d33pspace** [comment]
@kolte Beautiful. Thanks.
