### ISSUE TITLE
move this to the viewshared.cshtml 

### ISSUE THREAD

**Issue by jmurekezi** [d33pspace/RenewalWebsite#54]
https://github.com/d33pspace/RenewalWebsite/blob/1accf46d2d328eabbfd5fe2d738733a754f5affa/RenewalWebsite/Views/Manage/_PaymentHistory.cshtml#L6

will speed up the loading

**Comment by kolte** [comment]
It is not used in any other pages so no point adding it in viewshared page.

**Comment by d33pspace** [comment]
Thank you. Archiving this issue to revisit at a later date.
