### ISSUE TITLE
my opinion

### ISSUE THREAD

**Issue by jmurekezi** [d33pspace/RenewalWebsite#56]
I have a small issue in trying to understand the architecture of the application. lots of views could be put into one and then controlled by actions> as an example: the resetpasword and confirmation can be one view and you will have an actiontype to differentiate what is shown/actioned. same for payment and repayment etc this would reduce the repetition.
controllers seems to be doing a lot of logic and this is visible because of dependencies injected.
If I see anything I will add it here.

Also check some duplicated key in the css like on developer.css line 17 is duplicated
utilitypdf class looks very huge as well

**Comment by d33pspace** [comment]
The password reset feature is part of [ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio) so my instinct has been not to mess with it. However, I share your concern with the repetition involved with payment and repayment. @kolte What do you think?

**Comment by d33pspace** [comment]
There is a lot of redundancy in Payment, RePayment, CampaignPayment and CampaignRePayment. @kolte - you know best about the complexities involved here, but I'd like to see this refactored into one payment page if possible.

**Comment by d33pspace** [comment]
Thank you. Archiving this issue to revisit at a later date.
