### ISSUE TITLE
The translation of subscription management page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#57]
Hi @kolte and @d33pspace, I noticed the translation of the subscription management page has been changed to something not so right. Please remind me in case you are going to change some translation :) I wish I can do a verification before you perform the change.

Here's what we need to update/change back now,

![image](https://user-images.githubusercontent.com/42002784/44532020-b6108f80-a724-11e8-9076-5d79488ac4e7.png)

1. 季刊 should be 每季
2. Please remove the rmb symbol here ￥, as it's in USD now (you can see the currency after)
3. 活性 should be 有效

**Comment by d33pspace** [comment]
@kolte I've made the translation corrections, please remove the currency symbol. Note because USD is present in the next column no currency symbol is necessary for both Chinese and English. (There is currently no currency symbol for English.)

**Comment by elainetao829** [comment]
Verified and confirm fixed.
