### ISSUE TITLE
The card should be Master Card, but it shows on card management page as visa.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#58]
The card is a master card. See the screenshot of donate page.
![image](https://user-images.githubusercontent.com/42002784/44532246-3f27c680-a725-11e8-88f4-e4b9b7b5d0e5.png)

The screenshot of Stripe
![image](https://user-images.githubusercontent.com/42002784/44532260-4a7af200-a725-11e8-9763-69936cdaec73.png)

Actual Result:
It's VISA on the card management page.
![image](https://user-images.githubusercontent.com/42002784/44532298-61214900-a725-11e8-8938-535f3d153bf7.png)

**Comment by elainetao829** [comment]
Please let me know the Visa or Master Card icon here is a real one or a fake one.

**Comment by d33pspace** [comment]
@kolte Please make sure the card icon shows correctly on the card tab of the user management area.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
