### ISSUE TITLE
The button for adding a new card is not correct.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#59]
Steps:
1. User opens card management page.
2. User deletes the card saved before.
3. User checks the button now. 
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/44532452-b8271e00-a725-11e8-8e05-50cc4ef30579.png)

The button is ADD A NEW SUBSCRIPTION, and user clicks will go to the subscription page.

Expected Result:
The card should be
ADD A NEW CARD  (for English)
新增一张卡片 (for Chinese)
and user clicks would go to create a new card page.

**Comment by d33pspace** [comment]
Hi Elaine, the idea here is once the user removes their card, their customer record with our payment provider has been removed, and they should go through the full process of making a gift to add another card. But I agree this is confusing. What would you think of the button saying "Make a gift" instead of "Add new subscription"? Would this solve the problem?

**Comment by elainetao829** [comment]
editableHi Jimmy,

Along with Issue #19 , I think we can change the workflow here. 

I don't want to ruin here with my stupid ideas so I went to Amazon again :)

Here is the card management page of Amazon.

![image](https://user-images.githubusercontent.com/42002784/44564554-24da0100-a796-11e8-981c-ee4e9da711a9.png)

There are two buttons for one card, Delete and Edit.

If user clicks Edit, there is only two things editable. Date and Name.

![image](https://user-images.githubusercontent.com/42002784/44564604-666aac00-a796-11e8-8f63-c731237e7b5d.png)

The add new card button is somewhere below in a seperate block.

If we don't want to support multiple cards, we can make the current page as,

BANK CARD ***4333
Button EDIT     Button DELETE

The add a new card button will not show up if there is a card stored. User clicks ADD A NEW CARD, it should work the same as "EDIT" button now, i.e. provide an empty form for user to fill in. 

And you can remove the EDIT button before if you think there is nothing worth editing.

**Comment by elainetao829** [comment]
Hi @d33pspace,

1. I checked and I think the current solution is good. We can use this.

2. There are some translations need to be updated.

![image](https://user-images.githubusercontent.com/42002784/44797110-f5d1ee00-abe0-11e8-8482-c78b7a6269c8.png)
期限 --> 有效期

卡确认的价值 --> 安全码

For your security ... --> 为了您的安全, 日新中心不会存储信用卡详细信息。Stripe是我们的安全支付提供商。 

Please also change the 截止日期 to 有效期 here.

![image](https://user-images.githubusercontent.com/42002784/44797239-4c3f2c80-abe1-11e8-960d-81857e63560e.png)

**Comment by elainetao829** [comment]
Verified and confirm the labels are translated correctly on all pages related.
