### ISSUE TITLE
Delay when submitting preference update

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#6]
When a user submits email communication preference updates, there is an unusual delay when clicking the submit button. Can we do something like immediately change the button text to "Please wait..." upon clicking - or - grey the screen and display a round spinning counter immediately upon clicking the button until the task is complete?

To reproduce the issue:
1. Follow the link: https://staging.renewal365.org/preference?email=jimmy@renewal365.org 
2. Click the Submit button. There is an unusual delay of sometimes up to 10 seconds.

![screenshot 85](https://user-images.githubusercontent.com/13606352/43439379-86dc0328-94c5-11e8-8754-cd6c715c3fd4.png)

**Comment by d33pspace** [comment]
I understand. What I'm asking is if before you send the request to Zapier is it possible to change the button text to "Please wait..." or grey out the page and start a spinning timer, then when the request completes the confirmation page displays? This will clearly indicate to the user the process will take a few seconds.

Again, I'm not sure if this is possible. Just asking...

**Comment by d33pspace** [comment]
This is looking good. The Submit button changes to Please Wait with spinning graphic immediately upon clicking. However, it seems that once the process is complete, the button (or page) reverts back to the previous Submit state for a moment (sometimes several seconds), and then the confirmation message is displayed, but only very quickly - - there should be a 30 second delay before forwarding back to the home page.

I'm thinking there may even be another better way to accomplish this? You know better than I do. Perhaps waiting on Zapier can be an asynchronous process in the background that the user doesn't need to wait on?

**Comment by d33pspace** [comment]
@kolte This is looking good, but the update confirmation only displays for about two seconds. Please display the message for 30 seconds.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
