### ISSUE TITLE
Invoice history navigation and table

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#61]
If a user has no invoice history, do not display buttons, simply display, "No history." 

If a user has invoice history, just as in the PDF, display, "A record of your giving from August 23, 2017 to August 23, 2018." Below, display the table just as it was before. Below the table, display the buttons, including the PDF download button.

If there is no history in the date range selected, display, "No history" and also display all the buttons, **except** for the PDF button.

![screenshot 166 _li](https://user-images.githubusercontent.com/13606352/44559347-141c9180-a77c-11e8-8153-1f67fd148a9d.jpg)

**Comment by d33pspace** [comment]
This is partially implemented, thank you. 

As mentioned above, if a user has no invoice history, do not display buttons, simply display, "No history."

Also as mentioned above, when a user has invoice history displayed, just as in the PDF, display, "A record of your giving from August 23, 2017 to August 23, 2018."

See the two screenshots below for further detail.

![screenshot 169 _li](https://user-images.githubusercontent.com/13606352/44616159-47931500-a87d-11e8-800c-e81cd815f9a5.jpg)
![screenshot 173 _li](https://user-images.githubusercontent.com/13606352/44616164-537ed700-a87d-11e8-9de8-398da0c88e84.jpg)

**Comment by elainetao829** [comment]
Hi @d33pspace 

I may missed something. What content should be included in the table? I noticed on the website there is an additional column Method, which is not in the PDF. Do we really need it?
![1](https://user-images.githubusercontent.com/42002784/44798878-359ad480-abe5-11e8-83ef-7dec0443b87a.png)

**Comment by elainetao829** [comment]
2. There is a space before the date range, and all buttons. Do you think it would be better to make them left aligned?
When there is no history
![image](https://user-images.githubusercontent.com/42002784/44799078-a9d57800-abe5-11e8-8ff2-74b75b019137.png)
When there is some history
![image](https://user-images.githubusercontent.com/42002784/44799185-e43f1500-abe5-11e8-929d-69414dabf716.png)

**Comment by elainetao829** [comment]
3. When is no history at all, I don't see the "No history." message and the making gift button now. Please add them.

![image](https://user-images.githubusercontent.com/42002784/44799339-43048e80-abe6-11e8-8764-3d66895a8b7e.png)

**Comment by d33pspace** [comment]
Flowchart for this tab:
1. If a user has no invoice history, display "No history." Do not display table navigation buttons or email confirmation button.
2. If a user has invoice history, determine whether to require email confirmation to display history.
     (a) All currently existing accounts do not require email confirmation.
     (b) All new accounts that **do not** have a matching record (email) in InvoiceHistory do not require email confirmation.
     (c) All other accounts require email confirmation, in other words, all new accounts that have a matching record (email) in the InvoiceHistory table.
Another way to explain this confirmation step is, we have lots of history already uploaded to the InvoiceHistory table, but only a fraction of these people have accounts on our website. We do not want someone to be able to sign up under someone else's email address and be able to view their history. Therefore, email confirmation is required for **new** users with data in the InvoiceHistory table.
3. If a user has invoice history, display the last 12 months of data by default. If data exists, but no data is found for this time range, display the message, "No contributions found for this date range."

**Comment by elainetao829** [comment]
Hi @d33pspace,
Thanks for the summary. My only question is, why people do not have email set up before can check their history? How can they log in the system without any email registered before? Also, have you ever denied the email confirmation desription/wordings with Girish? It would be even better that you can define the detailed content for this part. Thanks.

**Comment by elainetao829** [comment]
1. Expected Result: all Chinese language PDFs do not contain the "fine print" about the 501(c)(3).
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/45153623-3c3dd300-b207-11e8-8b39-b012b980b499.png)

**Comment by elainetao829** [comment]
2. Expected Result:
(c) For English language users, table results that have only CNY also have a "Show USD conversion" link.
So for Chinese language users, there should no such option.

Actual Result:
![image](https://user-images.githubusercontent.com/42002784/45165209-e11bd880-b226-11e8-8699-608cf7fe9cf5.png)

**Comment by elainetao829** [comment]
3. When the money is USD already, please set the rate to 1, otherwise it looks weird.

![image](https://user-images.githubusercontent.com/42002784/45165437-669f8880-b227-11e8-8d74-3f04f05d961f.png)

**Comment by d33pspace** [comment]
@kolte Just one small thing here, please do not show the "Show USD conversion" checkbox when Chinese language is selected. Screenshot below:

![image](https://user-images.githubusercontent.com/42002784/45165209-e11bd880-b226-11e8-8699-608cf7fe9cf5.png)

**Comment by kolte** [comment]
All points are done except the first one, because those are the font how they look, we will need to change the font for this I think

"all Chinese language PDFs do not contain the "fine print" about the 501(c)(3)."

@d33pspace @elainetao829

**Comment by d33pspace** [comment]
@elainetao829 Can you please give all the issues raised here a good testing? My intent last time assigning this to Girish was only to not show the USD conversion checkbox when Chinese language is selected. But according to his last comment it sounds like he may have also revisited a few points that were already taken care of. In regards to the "fine print" he mentioned. There should now be some fine print on the Chinese PDFs (in Chinese), but it should not refer to the 501(c)(3). It should only say something along the lines of "no goods or services were provided." And of course I'm not talking about the font weight when I say "fine print" - I'm referring to the legalese at the bottom of the page. 

Since this thread is now a mess, if any further action is required here please close this and open in new issue(s).

**Comment by elainetao829** [comment]
Verified and confirm most of the issues have been fixed. The only pending issue has bee opened separately.
