### ISSUE TITLE
There is sometimes a blue outline around buttons

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#64]
There is sometimes a blue outline around buttons when active. For example in the screenshot below, I tabbed to this button. It should actually be red on white background when selected, but I don't care about that, I'd just rather not see the blue outline ever on any button.

![screenshot 172 _li](https://user-images.githubusercontent.com/13606352/44616203-00f1ea80-a87e-11e8-8373-4870e92f65c7.jpg)

**Comment by elainetao829** [comment]
Verified and don't see the blue outline. Close now.
