### ISSUE TITLE
Remove pop-up confirmation in favor of browser message

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#65]
I'd prefer a simple browser message here. In general, I prefer standard default behaviors and built-in controls over JavaScript. Additionally, I don't like animation or anything 3D. :) Please note this pop up confirmation appears both on the "Recurring gifts" and "Card" tab, and anywhere else it appears I'd like it replaced with a browser message.

![screenshot 171 _li](https://user-images.githubusercontent.com/13606352/44616214-53cba200-a87e-11e8-9a6f-907d227f89ed.jpg)

**Comment by elainetao829** [comment]
Verified both delete donation and card page. The dialog has been changed to the browser one. However, I noticed if user opens the dialog more than once (click the Cancel button again and again), there will be a checkbox asking user if he/she wants to block this dialog in the future.
![image](https://user-images.githubusercontent.com/42002784/44715901-88906100-aaeb-11e8-89e6-da05ee161a27.png)

I think we should get rid of this checkbox. If user set this checkbox as true by accident, he/she will not see this dialog again, i.e. the card or subscription cannot be deleted. User clicks the Cancel button and nothing happens. User has to refresh the page again to get the dialog back.

If you want to keep the checkbox, then I think we need to translate it into Chinese as well.

**Comment by d33pspace** [comment]
@kolte Is it possible to disable the message which says, "Prevent this page from creating additional dialogs?"

**Comment by d33pspace** [comment]
I'm sorry. Reopening for your final confirmation.

**Comment by elainetao829** [comment]
I agree with you @d33pspace. I'm closing this now.
