### ISSUE TITLE
Require email confirmation to enable History tab functionality

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#66]
For **new** accounts that have an email that **matches an email in the InvoiceHistory table Email column**, require email confirmation before the content of the History tab is displayed. 

Existing users > Email confirmation not required.
New users who do not have a matching email in InvoiceHistory > Email confirmation not required.
New users who have a matching email in InvoiceHistory > Email confirmation required.

This prevents a user signing up under an email address they don't own and viewing another's invoice history. If the scheme above make implementation complicated, simply require email confirmation for all users to view the content of the History tab.

Note that I do not want email confirmation required immediately upon registration of a new account, only to view the contents of the History tab. 

For users without access to History tab content, display the message, "To use this feature, please first confirm your email address." And a button below, "Send confirmation link".

**Comment by elainetao829** [comment]
@kolte 
Here is the translation. Thanks for waiting.

To use this feature, please first confirm your email address.
--> 使用此功能前，请先验证您的邮箱地址。

Send confirmation link
--> 发送验证链接

**Comment by elainetao829** [comment]
@d33pspace I was trying to test this ticket with account invoices@renewal.org.cn as that is the only account I know has a history. But I didn't see the verification messages there. Has someone already verified the email for that account? How should I test this scenario? 

It would be better if you can create some history for my account elainetao829@163.com so that I can really see the verification email.

**Comment by d33pspace** [comment]
Good point, we need to test 3 scenarios here: 

1) We don't want any _existing_ users to have to confirm their email. Any invoice history should show up. You can test this using invoices@renewal.org.cn and I also added a gift in 2010-9-1 for your 163.com email. I made that an early one that will be out of the typical range so you should have to select all history to see it. But again, for these, no email confirmation required.

2) We want _new_ users who already have giving data to have to confirm their email address. So what I've done is removed your qq.com address from the user table, and added a gift for 2018-9-1. So you should have to go through the new account process for this account, and the history tab should ask for you to confirm your email. Note that we could have unexpected problems with this. I'm not sure what the implications are of simply deleting a user from the user table.

3) We want _new_ users who have not given a gift yet to be able to see their gift when it's entered without email confirmation. So for this, create a new account when you are testing, it doesn't need to be a real email, you can use a renewal365.org address for it - - then tell me when you've done it, and I'll add a gift to the table, and you should be able to see it.

So again, summing up the concept here because it's confusing: only _new users_ who have preexisting historical data should have to confirm their email. Currently registered users, and new users without preexisting historical data do not have to confirm because there is no risk of them seeing someone else's data.

Also, if possible let's combine issue #61 and #23 here. The latest with #23 was the PDF button was not working at all. If that is still the case I'd like to bring it to Girish's attention to resolve immediately. (I don't want to drop these issues, for example, I still want PDFs to be downloadable on Andriod phones.)

**Comment by elainetao829** [comment]
Hi @d33pspace,
1. So for scenarios above, it means only new users who have a gift before creating the account needs to confirm their email, is that correct?
2. #23 still exists. But I would prefer we leave it there instead of combining @23 with this together. They are on the same page but for different functions and themes. :)
For #61 It's fine I will close that and test here.

**Comment by elainetao829** [comment]
As this is a complicated case, I'll write down what I tested here. Actually I think it would be even clear we use this ticket as a master feature, and open bugs in new tickets and link to this one. @d33pspace but I'm not sure if you agree with this.

1. Logging in with an existing account which has a history (elainetao829@163.com).
Expected Result: No email confirmation required.
Actual Result: Email confirmation required.
![image](https://user-images.githubusercontent.com/42002784/45152348-54135800-b203-11e8-89eb-916dfdc2ee65.png)

2. Registering new email account which has a history (46208601@qq.com)
(1) Is the purpose of the confirmation is to confirm (a) the viesing history (permission) or (b) to check whether the email is valid or not? I Currently the message and the email content are talking about (b) while I think it's for (a).
(2) The email is not translated into Chinese. Even I clicks the link when the language is Chinese, I still receive the English email.
I will provide the Chinese content after @d33pspace confirms the (1)
(3) The translation for the message "Link for view invoice history sent successfully." is not correct. 
I will provide the Chinese content after @d33pspace confirms the (1)
(4) The translation for the confirmed page is not correct (https://staging.renewal365.org/manage/invoicehistoryconfirm?UserId=3e5cbcc5-eb41-4b90-87cc-157e156ad665&Code=CfDJ8ORPwPDgiVBInEpcmQDz6WGOtgb4LfqxLLSFVd9JNcoZBCIrlrtEzY8sYO9p7%2FBrmVZKWH0YVnwxegbVLFTLiMxl8pZ1Mpd457r8ALUd%2BPnjN1ESHe7VlnInfcv86XNxZ6GgmGXJxUgWUvXAJujwwkb14gFxnqcDHZZO84HJBdleTKBBZA2OizYasePG%2BGDJZNgHpHIXBI961NIRKc4l0tVwpb1cZUy28tCVrCuIPV%2Bmd%2FoCmgoZm2abN14FkGIUBQ%3D%3D).
Again, I will provide the content later.
(5) The workflow is not correct on the confirmed page. It asks me to log in while I'm already logged in.
![image](https://user-images.githubusercontent.com/42002784/45153042-4b238600-b205-11e8-86ac-60fa3326e30c.png)
![image](https://user-images.githubusercontent.com/42002784/45153069-5aa2cf00-b205-11e8-969f-9cdfa39f6863.png)
(6) New account starbucks@staging.renewal365.org has been registered. Please create a history for it. Thanks.

**Comment by d33pspace** [comment]
@elainetao829 Great work, thanks for this. 

For your questions above, "So for scenarios above, it means only new users who have a gift before creating the account needs to confirm their email, is that correct?" Yes. Exactly right. And I agree, let's not combine issues when it doesn't make sense. 

For the issues you raised, I took care of the translation issues 2, 3 and 4. Note that I changed the English a bit as well so in some cases the translation doesn't exactly match now, but as long as it makes sense in Chinese that's fine. Note that I've been using 捐赠历史 instead of 发票记录 and similar. But let me know what you think sounds best. We are calling this "invoice history" internally, but for English users, it's "giving history." 

If any more work is required on the translation (or English for that matter) please raise that in a seperate issue from the functionality as the wording/translation is something I can often take care of quickly.

I've added a gift to the database for starbucks. Please check that out and once you have testing on that we'll keep this issue open and pass it off to Girish to work on the functionality. And just an additional note here that I'd like to have Girish work on the button design in the email. 

Thanks!

**Comment by elainetao829** [comment]
3. Tested failed.
Expected Result:
We want new users who have not given a gift yet to be able to see their gift when it's entered without email confirmation. 
Actual Result:
Registered starbucks@staging.renewal365.org and added giving history later. It requires email confirmation as below.
![image](https://user-images.githubusercontent.com/42002784/45265010-ed4aa480-b477-11e8-911b-7aaec238cc93.png)

**Comment by elainetao829** [comment]
@d33pspace 捐赠历史 is much better than 发票记录。I was thinking of that too. But I gave it up for considering matching the English name. Please use 捐赠历史 as you suggested. 

If you want to test the translation here, please delete my account 46208601@qq.com.

**Comment by elainetao829** [comment]
@d33pspace Verified 2(1) (2) (3) (4). Separate tickets have been opened. Do you think I should delete these issues so that you can pass the left to Girish?

**Comment by d33pspace** [comment]
Yes, I'm lost in this thread. Please close this issue and if any related issues remain please open in separate tickets.

**Comment by elainetao829** [comment]
@d33pspace I've deleted extra comments.
@kolte please check my last comment above and fix the problems.

**Comment by d33pspace** [comment]
Thanks for cleaning this up. The remaining issues are clear. As I understand your comments here the giving history tab is functional, but a bit of a mess at this point. I'm pausing this issue so we can push an update to production this week and we'll pick this up immediately after.

**Comment by d33pspace** [comment]
@elainetao829 I've removed elainetao829@163.com from the User table, but the invoice history still remains. So signing in with this account should require confirmation as in scenario 1. 

Also to reconfirm scenario 3 please create another account and let me know once you've done it and I'll add a record to the InvoiceHistory table.

I've moved the issue with the multiple emails to issue #117 - I think a spinner should fix this because the button is disabled while the spinner is active. Let's use this thread only for issues related with the three scenarios for viewing giving history.

**Comment by elainetao829** [comment]
I registered a new real email, as I think I may need to verify the mail from Renewal. Please create a history for elainetao829@126.com for scenario 3.

**Comment by d33pspace** [comment]
Gift of 1111 CNY created on 9/15 for this email address.

**Comment by elainetao829** [comment]
For scenario 3, an account was registered, and then a history was added afterwards -- it should not require an email verification.
But it requires now.
![image](https://user-images.githubusercontent.com/42002784/45628456-b5baa880-bac6-11e8-8830-4a54f29a9719.png)

**Comment by d33pspace** [comment]
Hi @kolte - the current status of this issues is:

Scenario 1: Existing users do not require account confirmation: *Passed*
Scenario 2: New users **with** invoice history **require** account confirmation: *Passed*
Scenario 3: New users **without** invoice history **do not require** account confirmation: *Not passed*

So to further explain scenario 3, when we have a new user sign in and there is no record with a matching email address in the InvoiceHistory table, the account can be set to confirmed immediately. In other words, even though they have no invoice history yet, they will be able to see it without account confirmation as soon as a record with their email address is entered into the InvoiceHistory table.

**Comment by elainetao829** [comment]
elainetaoran@163.com has been registered. Please create a history for it.

**Comment by d33pspace** [comment]
Done.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
