### ISSUE TITLE
An outline left on the old tab while user switches different tabs in user management.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#68]
Steps:
1. User logs in.
2. User clicks the account and enters into account management part.
3. User switches between different tabs, e.g. details, and cards, and password.

Actual Result:
There is an outline left on the old tab while user switches to a new tab. 

It's impossible to do the screenshot for this one. So I took a photo with my phone. Please ignore the screen flash.

![image](https://user-images.githubusercontent.com/42002784/44732786-a7591c80-ab18-11e8-81f0-46c1cf02f2cf.png)

**Comment by d33pspace** [comment]
Strange! I wasn't able to reproduce this on any of my browsers. I'm thinking let's ignore this for now but please keep an eye on it as you test in different browsers and machines to see if you can find what's causing it.

**Comment by d33pspace** [comment]
@elainetao829 If you're able to reproduce this reliably feel free to send a video through Upwork, or close it for now.

**Comment by elainetao829** [comment]
Hi,
I would close this for now. Until I can reproduce it.
