### ISSUE TITLE
Add user information to EventLog

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#7]
Is it possible to add the signed in user's information to the EventLog table and notification emails?

**Comment by d33pspace** [comment]
This looks good. Just an additional question here: I don't seem to get notification emails from staging. Is the notification email set to send only for production? (If so, this is fine. I just want to confirm.)

**Comment by kolte** [comment]
yes, it depends on what email is configured in appsettings

"EmailErrorNotification": {
    "Email": "xyz@renewal365.org"
  }

**Comment by d33pspace** [comment]
This seems to be working fine.
