### ISSUE TITLE
Can user donate with (Chinese) debit card?

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#70]
Hi Jimmy,

Upon reading English content on our website, I always can see something like donate with "debit card or credit card". I don't know anything about American debit card, but can user donate with Chinese debit card? If yes, then we have to 1. update some translation as the translation always says "信用卡 (credit card)". 2. Chinese debit card does not have security code and validation date. How can you really charge money?

**Comment by d33pspace** [comment]
Good question. Internationally (outside of China) both credit and debit cards are accepted. Inside China, only credit cards are accepted. Let's make sure this is clear. For me, it's fine in English to say, "Credit or debit card" and the Chinese translation to be "信用卡" only. What do you think?

**Comment by d33pspace** [comment]
@elainetao829 At your convenience please suggest a change or close this.

**Comment by elainetao829** [comment]
@d33pspace I was checking the Chinese translation for this.

@kolte Since Chinese debtor card is not acceptable, please update the history tab of account management module,

![image](https://user-images.githubusercontent.com/42002784/44947620-38decc00-ae42-11e8-9a3f-d85ccaa896e2.png)

Please remove the yellow characters "或借记卡“.

For other places, it only says credit card in Chinese.

**Comment by d33pspace** [comment]
I've made the change. :)

**Comment by elainetao829** [comment]
Verified and confirm fixed.
