### ISSUE TITLE
The tool tip when the mouse hovers on the email field of communication subscription should be translated.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#71]
Steps:
1. User opens the website in Chinese.
2. User scrolls the page down to the bottom, and put the mouse on the field "email" in the communication subscription part. A tool tip/message would come out.
3. User checks the message.

Actual Result:
The message is in English. 
![image](https://user-images.githubusercontent.com/42002784/44838041-cae1ab80-ac6d-11e8-91c3-7f1c962bf814.png)

Expected Result:
The message should be translated into Chinese as,
请输入您的邮箱。

**Comment by elainetao829** [comment]
Also the tool tip when user puts the mouse on the account should be translated too.

Currently it's "Manage",

For Chinese page, it should be "管理“

**Comment by d33pspace** [comment]
Hi Girish, just to confirm both of these fields should be required. The tooltip for Name should be "Please enter your name." Translation: 请输入您的全名。 and the tooltip for Email should be "Please enter your email." Translation: 请输入您的邮箱。

Actually I don't care if there are tooltips, just preventing erroneous submissions.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
