### ISSUE TITLE
Chinese improvement on payment page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#72]
Hi, 

“您的每年捐赠$xx” is translated correctly. But not so Chinese.  
![image](https://user-images.githubusercontent.com/42002784/44844279-09329700-ac7d-11e8-9465-2c1a4ef03ff6.png)

Can we change it into
您将每年捐赠$xx.xx

which means "you will donate $xx every year"

Please remember to update for both the regular payment and campaign payment as I'm not sure if they are the same pages.

**Comment by elainetao829** [comment]
For quarterly, it should be
您将每季捐赠$xx.xx

monthly should be
您将每月捐赠$xx.xx

one time should be
您将一次捐赠$xx.xx

**Comment by d33pspace** [comment]
Done. Please check all 4 giving scenarios. Also, I think I noticed the name address labels ("Your name as you wish it to appear in our records..." and "The address where you'd like to receive our communications...") are still not perfect in all four scenarios, specifically Chinese. Could you please confirm all four pages are perfect in both languages? This is first time payment by (1) donate page (2) campaign page and second payment by (3) donate page and (4) campaign page.

**Comment by elainetao829** [comment]
@d33pspace I reviewed and didn't see the bug you mentioned. And I believe there was a ticket about that. I'm not sure if the bug was fixed because of that. Will keep an eye on this problem.
Please answer the questions above.

**Comment by d33pspace** [comment]
@kolte Please move the error messages Elaine highlighted above to below "Please enter your details below:" Please make sure all 4 relevant payment pages are updated, English and Chinese versions.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
