### ISSUE TITLE
The Chinese for the Name field when there is no value entered in. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#73]
On payment page, the message in the Name field should be translated into
姓名
when the field is empty.

![image](https://user-images.githubusercontent.com/42002784/44844751-5bc08300-ac7e-11e8-9751-688c0d5b0f16.png)

**Comment by elainetao829** [comment]
On details tab of user management, please also show 姓名 in the Name field when there is no value entered in.

![image](https://user-images.githubusercontent.com/42002784/44844863-8c082180-ac7e-11e8-9f76-bf7ae8b85d58.png)

**Comment by d33pspace** [comment]
I see 省 is also missing from inside the field in your screenshot. Should we add it?

**Comment by elainetao829** [comment]
@d33pspace I deleted our comments on purpose. I was wrong as on the payment field, there is no label above the field, but on the account management, there is label there. So we don't need to add the label again in the field. 

I checked the label Name has been translated correctly. I would close this now. Thanks.
