### ISSUE TITLE
The Chinese translation for the managelogins page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#74]
Steps:
1. User logs in with an external account and opens user management page.
2. User opens tab Password.
3. User opens page external account management.
4. User checks the registered external account.

Actual Result:
The registered external account is still English.
![image](https://user-images.githubusercontent.com/42002784/44845170-67f91000-ac7f-11e8-97ea-71885a6b8488.png)

Expected Result:
Please translate into
谷歌  (for Google)
脸书 (for Facebook)
微软 (for Microsoft)

**Comment by d33pspace** [comment]
@kolte Could you take care of this please, these can be tricky for me.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
