### ISSUE TITLE
Adding a new external account leads to 404. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#75]
Steps:
1. User logs in with an external account and opens user management page.
2. User opens tab Password.
3. User opens page external account management.
4. User clicks Facebook/Google/Microsoft below to add a new external account.

Actual Result:
404 not found.
![image](https://user-images.githubusercontent.com/42002784/44845325-d1791e80-ac7f-11e8-955b-39430447594a.png)

**Comment by d33pspace** [comment]
@elainetao829 I believe we have this issue existing already, can you please take a look and either close this one or if it's related but different, consider consolidating into one?

**Comment by elainetao829** [comment]
Duplicate.
