### ISSUE TITLE
Entering symbols or special characters in the donate amount field leads to 404 page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#76]
Steps:
1. User opens the donate page.
2. User enters symbols or special characters as the donate amount.
![image](https://user-images.githubusercontent.com/42002784/44845476-37fe3c80-ac80-11e8-9c38-90550a9394fe.png)
3. User clicks the Donate with Credit Card or Debtor Card button.

Actual Result:
404 not found.

Expected Result:
Error message would show up like,
Please enter a valid amount.
请输入一个有效的金额。 (for Chinese)

**Comment by elainetao829** [comment]
Hi,
1. On campaign donate page, entering any symbol, as -,= will still lead to 404 page.

2. On normal donate page, entering something like -7-09 will still lead to 404 page.

**Comment by d33pspace** [comment]
@kolte I'm not sure why the data validation here is such a problem. Can we not require a number between 0.5 and 100,000?

**Comment by elainetao829** [comment]
Sorry I still cannot close this. 
1. For both normal and campaign donate pages, if user enters "0-" now will still go to the 404 page. 
2. For campaign donate page, the error message is not translated.

**Comment by elainetao829** [comment]
![1](https://user-images.githubusercontent.com/42002784/45100106-6639bb80-b15b-11e8-808a-01ac02f76094.png)

**Comment by elainetao829** [comment]
The 404 page problem has been fixed. Another related small issue has been opened separately. See #98.
