### ISSUE TITLE
Entering an amount less than 0.5 and then switching the language would lead to a 404 page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#77]
Steps:
1. User opens Donate page.
2. User enters an amount less than 0.5, e.g. 00.
3. User clicks Donate with Creditor or Debtor Card Now. The system would show out an error message saying the amount should be greater than 0.5.
![image](https://user-images.githubusercontent.com/42002784/44845726-e5715000-ac80-11e8-89b6-32c6bddd6806.png)
4. User clicks the 中文 button on the top right now to change to Chinese.

Actual Result:
404 not found.

Expected Result:
The system would show out a default (no value entered and no error message) Chinese donate page.

**Comment by d33pspace** [comment]
@elainetao829 Could you explore this a little further please? I was not able to reproduce the 404, but when I followed your instructions and attempted to change to Chinese I was directed to the address/card details page which is also incorrect. Let's try a few different scenarios before we pass this on to Girish.

**Comment by elainetao829** [comment]
@d33pspace I tested again and it's related with Browser... Very strange I couldn't believe it even :)

I was testing with Firefox the 1st time, and just tried again -- it always goes to a 404 page.

I changed to Edge and  tried -- it went to log in page...

**Comment by elainetao829** [comment]
Verified and confirm fixed. Tested on different browsers.
