### ISSUE TITLE
The layout of setpassword page.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#78]
Steps:
1. User logs in with an external account.
2. User opens account management page.
3. User opens tab Password.
4. User clicks Create password button. 

Actual Result:
The system opens a set password page. But the layout needs to be adjusted. And the words need to be translated.

**Comment by elainetao829** [comment]
![image](https://user-images.githubusercontent.com/42002784/44846073-e6ef4800-ac81-11e8-8bf1-6d661cafe4dc.png)

For the English layout, since this is the 1st time user set a passowrd, it would be appropriate to name the fields as
Password
Confirm password

Same as Register page, but different from change password page.
Also please keep Change password in one line, instead of two.



2. For

**Comment by elainetao829** [comment]
2. @d33pspace please consider the blue message here. It's not very clear. For example, what is "local username"? And it says user does not have a local username, but while user was logging in with the external account for the 1st time, the system has already asked him/her to enter an email address. I would assume that is an username.  
Also it asks user to add a local account, but actually user is only setting a password. Account should include name and password.

Please think it over and see if we can change the message here.

**Comment by elainetao829** [comment]
3. For the Chinese translation, I would provide later after @d33pspace decides whether we need to change the English message.

**Comment by d33pspace** [comment]
@kolte (1) Please make that blue message black and change it to, "Set a local password so you can log in without an external provider." (2) Please change "New password" to "Password" and (3) Change "Confirm new password" to "Confirm password" and make sure it doesn't wrap to two lines.

**Comment by kolte** [comment]
@d33pspace @elainetao829 can you please give me translation for this?

**Comment by elainetao829** [comment]
Hi @kolte, the English version is fine now. The corresponding Chinese translation needs some small updates.
1. 新密码长度必须在6--100个字符之间。 --> 密码长度必须在6--100个字符之间。
2. 两次输入的密码不一致。
3. 设置本地密码，以便您可以在没有外部提供程序的情况下登录。 --> 请设置网站密码，之后您可以直接登录而无需使用第三方账户。

**Comment by elainetao829** [comment]
Verified and confirm fixed.
