### ISSUE TITLE
The Change Password page is not translated.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#79]
Steps:
1. User logs in with an account with password.
2. User opens account management page.
3. User opens tab Password.
4. User clicks the change password button.
5. User changes the page into Chinese.

Actual Result:
The English layout is not consistent with Register and Reset Password page.
And the page is not translated.
![image](https://user-images.githubusercontent.com/42002784/44858684-23806b00-aca5-11e8-87b5-4855b2d4def5.png)

Expected Result:
For English,
Change Password. --> Change Password (remove the period)
Change password form --> Change your password. 

For Chinese translation,
Change Password  --> 修改密码
Change your password. --> 请修改您的密码。
Current Password --> 当前密码
New Password --> 新密码
Confirm New Password --> 再次输入新密码
The New password must be at least 6 and at max 100 characters long. --> 新密码长度必须在6--100个字符之间。
The new password and confirmation password do not match. --> 两次输入的新密码不一致。
Incorrect password. --> 密码不正确。

**Comment by d33pspace** [comment]
@kolte I made the translation changes to the page itself. Can you take care of the messages please?

**Comment by kolte** [comment]
@elainetao829 can you please provide this transactions?
![image](https://user-images.githubusercontent.com/8025877/44897595-d68aac00-ad19-11e8-8ce7-9ae33ee0f911.png)

**Comment by elainetao829** [comment]
The Current password field is required. --> 请输入您的当前密码。
The New password field is required. --> 请输入您的新密码。

**Comment by elainetao829** [comment]
Sorry I cannot close this.

Incorrect password has not been translated.

![image](https://user-images.githubusercontent.com/42002784/45100760-9df53300-b15c-11e8-9352-4970fcf79f93.png)

Following our translation style here, please translate the message into "您输入的当前密码不正确“。

**Comment by elainetao829** [comment]
Now it's 密码不正确。 Although it's not exactly the same as I required above, it's acceptable. So I'm closing this.
