### ISSUE TITLE
Change "expiration month" to "expiration date" in error message.

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#81]
This error message should read, "Your cards expiration date is invalid." @elainetao829 The current translation is: 您的卡的到期月份无效。Would you like to update that based on this change? Please record the proper translation then tag for @kolte 

![screenshot 184 _li](https://user-images.githubusercontent.com/13606352/44906202-d6ed6c00-ad46-11e8-826f-f8a48377c387.jpg)

**Comment by elainetao829** [comment]
Hi @d33pspace,
Before checing this issue, I have opened a new one #85 for the translation problem. Since there are also some other words need to be modified, I think it would be better @kolte change the translation in that ticket and only update the English words here.

**Comment by kolte** [comment]
@elainetao829  Validation message of card coming from stripe
