### ISSUE TITLE
The error messages are not correct or consistent when CVC or card number or expiration date is not valid/missing. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#85]
Actual Result:
The error messages are not correct or consistent when CVC or card number or expiration date is not valid/missing. 
For example,
1. On card tab of account management module, when the CVC number is not entered, the message is still in English.
![image](https://user-images.githubusercontent.com/42002784/44944941-58f69700-ae12-11e8-8d80-4f9f9ce9c69d.png)

2. On card tab as well as the payment page, when CVC number is not valid, the message is a combination of Chinese and English.

3. On card t ab, when card number is missing, or the expiration date is not valid, the messages are English only. 
![image](https://user-images.githubusercontent.com/42002784/44944899-7c6d1200-ae11-11e8-9256-95b7de73aad3.png)

![image](https://user-images.githubusercontent.com/42002784/44944914-ceae3300-ae11-11e8-8a99-be753906ec05.png)

Expected Result:
We need to improve and update the error messages as below for all pages (including campaign payment, donate payment and card management), to make them to be the same. 
When card number is missing. -->请输入您信用卡的卡号。
When card number is not valid. --> 您输入的信用卡卡号无效。
When expiration date is missing. --> 请输入您信用卡的有效期。
When expiration date is not valid. --> 您输入的截止日期无效。
When CVC field is missing. --> 请输入您信用卡的安全码。
When CVC field is not valid. --> 您输入的安全码无效。

**Comment by d33pspace** [comment]
@kolte Please update the translation of these error messages and Elaine suggests above. Note this is related to issue #81 as we also need to change the English "expiration month" to "expiration date".

**Comment by d33pspace** [comment]
@elainetao829 I'm sorry can we close and rework this issue to clarify? I confused things further with the comment about "expiration month" but that's apparently a message from our payment provider so please ignore that.

1. Are you suggesting that the error message above the tabs be moved down below the heading with the other messages? I agree, I just want to make sure I've got that right.

2. For the error messages can you please recreate the list in this format: "(English message) --> (Correct Chinese translation)" This will work whether there is no translation or the translation is incorrect.

**Comment by elainetao829** [comment]
English message: Credit Card Number is required.
Incorrect Chinese message: 信用卡号是必需的。
Correct Chinese message: 请输入您信用卡的卡号。

English message: Invalid Card Number
Incorrect Chinese message: 无效卡号
Correct: 您输入的信用卡卡号无效。

On card tab of account management page,
Incorrect English message: The Cvc field is required.
Correct English message:  Security Code is required.
Incorrect Chinese message: (not translated)
Correct Chinese message: 请输入您信用卡的安全码。

On (normal and campaign) payment page,
English message:  Security code is required.
Incorrect Chinese message: 安全码是必需的.。
Correct: 请输入您信用卡的安全码。

Incorrect English message: Invalid CVC number.
Correct English message: Invalid Security Code
Incorrect Chinese message: 无效的CVC号码。
Correct Chinese message:  您输入的安全码无效。

English message: Your card's expiration month is invalid.
On card tab of account management: Incorrect Chinese message: (not translated)
On payment page: Incorrect Chinese message: 您的卡的到期月份无效。
Correct: 您输入的截止日期无效。

**Comment by elainetao829** [comment]
Hi @d33pspace 
1. Sorry for the confusing, I don't mean we need to change the position of the error message. I just want to change the content of the messages. If you think the position is not correct either, we can open a new issue.
2. I've reworded the ticket as above. Please feel free to replace the ticket content and delete extra comments to avoid confusion for the developers.

**Comment by d33pspace** [comment]
@elainetao829 Thank you for the clarification! I've made changes to the translations (1), (2), (4), (5) above. Please first check and confirm these in all four payment scenarios and account management card tab as applicable. If those issues require further work, let's continue dealing with those in this thread.

For (3) I will need Girish's assistance because this string is composed dynamically, please open this in a new issue and detail exactly where it occurs with screenshots (e.g. payment process, account management card tab). 

For (6) I made the correction in the payment process, but I will need Girish's assistance for the account management card tab. Please test the change in the payment process and if any further update is required comment in this thread, for the card management tab, please open this in a separate issue.

**Comment by elainetao829** [comment]
Hi @d33pspace,

For (1) (2) (4) (5) there is a small issue left as below.
![image](https://user-images.githubusercontent.com/42002784/45365002-2288fb00-b60e-11e8-8eec-c15d392ca4e5.png)

For (6) the payment page is OK now and wait for Girish to work on the card management page.

For (3) not tested yet and wait for Girish's work.

**Comment by d33pspace** [comment]
Continuing work under issue #109.
