### ISSUE TITLE
The tab name is not correct for campaign related pages. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#86]
Actual Result:
The campaign payment page's tab is not translated.
![image](https://user-images.githubusercontent.com/42002784/44945035-b3442780-ae13-11e8-8ab1-2aa56ef24007.png)

Expected Result:
It should be translated into 日新中心|捐款  (@d33pspace ) do you want to make it different with the normal donate? I see the English tabs name are the same.

**Comment by elainetao829** [comment]
2. Actual Result:
The payment page for both campaign and normal donate is 
For English, Renewal | Credit Card
For Chinese, 日新中心 | Credit Card
![image](https://user-images.githubusercontent.com/42002784/44945068-103fdd80-ae14-11e8-8386-c6b298f33acd.png)

@d33pspace should we change the English name as well? It's not a credit card, but a payment page.
If you agree, we can change it into 
For English, Renewal | Payment
For Chinese, Renewal | 付款

**Comment by d33pspace** [comment]
Thanks. I made this change.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
