### ISSUE TITLE
The workflow of email subscription.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#87]
Hi @d33pspace,

I subscribed my email long time ago and received the 1st email. However, in order to test that email in Chinese again, I tried lot unsubscribe (through the link in the email) and subscribe again (through the home page of Renewal). But the testing was failed as I waited but couldn't receive the email afterwards.

Is this a bug or how does the workflow look like?

**Comment by d33pspace** [comment]
Sorry. I'm sure I unsubscribed you. I regularly unsubscribe any email that looks like it may have been used for testing. Also note that I'm working on a new footer which includes a new unsubscribe link, it is now active in the first mail you receive upon subscription, but be sure to manually change the URL from www.renewal.org.cn to staging.renewal365.org. This being said, the new footer and links are not quite ready for testing.

**Comment by elainetao829** [comment]
@d33pspace so if you also unsubscribed me, I should be able to subscribe again? However, I tried the email subscription with elainetao829@163.com, but there is no email received. Can you please check what happened?

**Comment by d33pspace** [comment]
Hi Elaine, I checked our email system. It has recorded that you've subscribed and unsubscribed 3 times with both e****9@163.com and e****1@163.com. The system is a little fussy and tries to prevent hacking and abuse so you may have triggered something that is not allowing you to subscribe again with these addresses. I've just tested myself and there is no problem with the subscription process. Do you have other accounts you can subscribe with? If you need to we can set you up with some Renewal testing accounts with no problem.

**Comment by elainetao829** [comment]
@d33pspace I just suscribed another email 46208601@qq.com, and there is no email received either. Could you please check for me?
p.s. for this qq mailbox, I never subscribed before.

**Comment by elainetao829** [comment]
@d33pspace I didn't see the subscription way you mentioned, nor in Upwork either. Could you please let me how can I subscribe now?

**Comment by d33pspace** [comment]
Try this:
https://www.getdrip.com/forms/311250575/submissions/new

**Comment by elainetao829** [comment]
Hi @d33pspace 
Unfortunately, the link is not working either :)

![image](https://user-images.githubusercontent.com/42002784/45098048-c843f200-b156-11e8-96d7-db79f73588ab.png)

I tried both of my mail addresses (elainetao829@163.com, and 46208601@qq.com), both got the same error: recaptcha is not valid. And I tried them with VPN again, and still got the same error message.

**Comment by d33pspace** [comment]
Hi. You will need to use VPN here because the captcha is Google. Did you see it? For me it was just a checkbox that said, "I'm not a robot." In any case, I've submitted your 163.com email so you should have received a confirmation email at that address, once you follow it, you should be able to subscribe again through the website. Please WeChat me if you continue to have issues with this so we can get it worked out!

Oh, I tried to submit your qq.com address, but it said qq.com is a "high-bounce domain" and it wouldn't accept it.

**Comment by elainetao829** [comment]
It works now. @d33pspace thanks for your help. I'll close this ticket.
