### ISSUE TITLE
The credit card would be deleted if user enters a new card number and submit on the payment page, even the payment was not successsful.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#88]
Precondition:
User saved a card before.

Steps:
1. User opens the payment page (donate or campaign).
2. User clicks Edit card button.
3. User enters a new card number, a valid CVC number, and an invalid Expiration Date, e.g. 01 2018.
4. User clicks Submit payment button. The system would show up the error message that the Expiration Date is invalid.
5. User opens Card tab of account management module.

Actual Result:
The old card is deleted. There is no new card now.

Expected Result:
Since adding a new card was not successful, I think we should not delete the old card now. @d33pspace what's your idea here?

**Comment by d33pspace** [comment]
Interesting. Let's explore this a little further. (1) Does the same thing happen when a card is declined (4000 0000 0000 0002) or the CVC is invalid (4000 0000 0000 0101)? What happens in the account management area when the user attempts to replace a card with a card with invalid details? 

It does make sense to me that if a user fails to provide valid details to change a card that the previous card is retained.

**Comment by elainetao829** [comment]
Thanks for the inspiration. Tested the following scenario,
Precondition:
A card has been saved correctly before.

Scenario A
1. On card management tab, click Edit button.
2. Enter an invalid card number, enter valid expiration date and CVC.
3. Click Save, see the error message.
4. Go to other page, and go back to card management tab again.
Actual Result:
The correctly saved card information is still there.

 Scenario B
Same as scenario A, but enter an invalid Expiration Date.
Actual Result:
The saved card information is still there.

Scenario C:
Same as A and B, but enter an invalid CVC number.
Actual Result:
The saved card information is still there.

Scenario D
Same as A, but make the change at the payment page.
Actual Result:
The saved card information is still there.

Scenario E:
Same as scenario E, but enter an invalid CVC number.
Actual Result:
The card information is still there.

Conclusion:
This bug occurs only at the payment page, and only occurs when user enters an invalid Expiration Date.

**Comment by d33pspace** [comment]
@kolte In case of expiration date error on payment page, do not delete the old card information.

**Comment by elainetao829** [comment]
Verified and confirm fixed.

**Comment by elainetao829** [comment]
It seems I forgot to test the campaign page and the bug is there as well. Please fix that.

**Comment by d33pspace** [comment]
@kolte You made this correction on the donate page, please make the correction on the campaign page as well. Please always check Payment, RePayment, CampaignPayment and CampaignRePayment for consistency when making changes like this.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
