### ISSUE TITLE
The Chinese word "每月一次” (monthly) for donation cannot be shown complelete. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#9]
Steps:
1. User opens Donate page in Chinese. 
2. User selects donate with credit card. 
3. User selects 每月一次 (once per month).

Expected Result:
每月一次should be shown properly in the field. 

Actual Result:
The field is too small for four Chinese characters. 

![3](https://user-images.githubusercontent.com/42002784/43529450-e6c17f3e-95dd-11e8-8db0-f4ab1d23916b.png)

Resolution: 1600*900

**Comment by d33pspace** [comment]
I haven't noticed this issue in Chrome, IE or Edge.

**Comment by elainetao829** [comment]
Verified and the bug has been fixed.
