### ISSUE TITLE
The campaign donate page in WeChat browswer on cellphone is not translated into Chinese. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#90]
Steps:
1. Open the website in WeChat browser from a smart phone.
2. Select the language as Chinese.
3. Open the campaign page from the home page.

Actual Result:
The campaign page is not translated into Chinese. 
![campaign](https://user-images.githubusercontent.com/42002784/45011266-3946b500-b044-11e8-9948-6bc2a108ef6b.jpg)

Expected Result:
The campaign page should be translated into Chinese as the normal donate page.
![normal donate](https://user-images.githubusercontent.com/42002784/45011276-4a8fc180-b044-11e8-98a3-89615b5732b5.png)

**Comment by elainetao829** [comment]
Please be kindly noted, the tab also needs to be translated.

**Comment by d33pspace** [comment]
Nice catch. I've made the correction here.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
