### ISSUE TITLE
can you please make this into a property and use it everywhere we have a call to retrieve users

### ISSUE THREAD

**Issue by jmurekezi** [d33pspace/RenewalWebsite#91]
https://github.com/d33pspace/RenewalWebsite/blob/f391119a4d9aeff3b5ac6d95f4a109a9a52c05b1/RenewalWebsite/Controllers/ManageController.cs#L104

**Comment by d33pspace** [comment]
Thank you. Archiving this issue. We'll revisit at a later date.
