### ISSUE TITLE
The Expiration month on credit card management page is not translated.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#94]
Actual Result:
The month is in English. 
![image](https://user-images.githubusercontent.com/42002784/45102097-79e72100-b15f-11e8-8e2d-732f8da16ceb.png)

Expected Result:
Please make this same as the payment page.
![image](https://user-images.githubusercontent.com/42002784/45102171-a438de80-b15f-11e8-8040-bc016cf7bbf0.png)

**Comment by d33pspace** [comment]
Thanks, Elaine. I agree. One question - should the order of the expiration month and year be reversed on the Chinese pages?

**Comment by elainetao829** [comment]
@d33pspace thanks for asking. But no. I checked all my cards issued by Chinese banks. The sequence is same as English, i.e. month / year.

**Comment by d33pspace** [comment]
@kolte Please remove Jan, Feb, Mar, etc. from the Expiration Month dropdown on the account management Card tab to match the Expiration Month dropdowns in the payment process. Only the month number is necessary . . . 01, 02, 03, etc.

**Comment by d33pspace** [comment]
@elainetao829 I've made this change. Please take a look. Also, will you please compare our Expiration Year to other sites. Do we have enough future years in there?

**Comment by elainetao829** [comment]
@d33pspace the card expiration date usually is sometime after 3 -- 5 years ---- I learned this from baidu and bing.
From this point of view, I think the expiration on Renewal would be enough. It's 10 years now.
Though I checked Amazon, the farthest card expiration month is 2038. I don't think we need that long. 
Or please open a ticket if you disagree.
