### ISSUE TITLE
The label of Name field should be Chinese if the page is in Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#97]
Steps:
1. User opens normal donate or campaign donate page in Chinese.
2. User empties the Name field.
3. User clicks other places on the page, e.g. the dropdown list of Country.
Actual Result:
![image](https://user-images.githubusercontent.com/42002784/45255760-3dfdc700-b3be-11e8-9b3c-eebae6897004.png)

Expected Result:
The label should be Chinese 姓名

**Comment by d33pspace** [comment]
Thanks. I made this correction.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
