### ISSUE TITLE
Entering a donate amount as "9-" will come out two error messages.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#98]
Steps:
1. User opens normal donate or campaign donate page.
2. User enters an amount as "9-" or "8-".
3. User clicks the Donate with Credit Card button.

Expected Result:
Only one error message, either in English or in Chinese.

Actual Result:
There is an extra message, exists for both Chinese and English page. Please remove that.
![image](https://user-images.githubusercontent.com/42002784/45255882-b82f4b00-b3c0-11e8-9e9a-3dace21c9162.png)

![image](https://user-images.githubusercontent.com/42002784/45255884-c8dfc100-b3c0-11e8-96da-bc1e10d1b344.png)

**Comment by d33pspace** [comment]
@kolte Please remove the superfluous error message highlighted in the screenshots above.

**Comment by elainetao829** [comment]
It's not removed for other invalid values.... Could you please check again?

![image](https://user-images.githubusercontent.com/42002784/45365616-8102a900-b60f-11e8-9f35-4c29f9b4820f.png)

**Comment by d33pspace** [comment]
@kolte Could you please correct the issue in the screenshot directly above? Please confirm both Donate and Campaign pages are corrected.

**Comment by elainetao829** [comment]
Verified and confirm fixed.
