### ISSUE TITLE
Switching the language on campaign payment page leads to 404. 

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalWebsite#99]
Steps:
1. Open Campaign donate page.
2. Select an amount and click Donate with Credit Card.
3. On the campaign payment page, leaves an required field empty, e.g. Name, and click Submit Payment button.
4. The system shows out error message, saying the Name is required. Click the language option on top right, English or Chinese.
Actual Result:
The system opens a 404 page. 

@d33pspace for normal payment, the system would go back to the home page in this scenario. Is that acceptable for you? Can we set the same pattern for campaign payment?

**Comment by d33pspace** [comment]
@kolte Please correct the path to the 404 from the campaign page as Elaine described above. On the donate page, the same behavior returns to the home page - - that is fine.

**Comment by kolte** [comment]
@elainetao829 @d33pspace 
I tried but not able to reproduce this error. can you please check?

**Comment by d33pspace** [comment]
@elainetao829 I also just tried and was not able to reproduce it.

**Comment by elainetao829** [comment]
I just tried and the problem is gone... not sure if it's fixed along with other issues. I'll close this for now.
